### ISSUE TITLE
Roadmap / Functional Spec

### ISSUE THREAD

**Issue by max3903** [OCA/field-service#1]
Functional specifications / roadmap:
https://drive.google.com/open?id=1ijTCc5p0Ex84Pntdyck0FamoyFKXAyfE_jqoiVBshgw

Technical specifications:
https://docs.google.com/document/d/1z625Rq1Lh6_7q-GmsbKV1O6f3tfDA_Mrg-f-f_6LxVU

Use cases:
https://drive.google.com/open?id=1pzG4btpOxx7SpYLx15NMgr4E0aIuFer6qlCtbiIT928

**Comment by max3903** [comment]
Ping @wolfhall

**Comment by JosDeGraeve** [comment]
hi @max3903 can you share the google docs ?

**Comment by max3903** [comment]
@JosDeGraeve I updated the links to copy of the original documents. Those new documents should allow you to comment.

**Comment by sbidoul** [comment]
cc/ @chrisdec

**Comment by janbec** [comment]
@max3903 
This sounds really interesting. If you need someone for functional testing, I'll be happy to help.

**Comment by etobella** [comment]
Do you intend to use it only in order to sell services or could be used for internal services?

**Comment by max3903** [comment]
@etobella The field service order can be invoiced or not.

If you have a use case in mind, please add it here:
https://drive.google.com/open?id=1pzG4btpOxx7SpYLx15NMgr4E0aIuFer6qlCtbiIT928

**Comment by MarkingSC** [comment]
Hello @max3903 , could you please share the Technical Specifications document?

**Comment by max3903** [comment]
@MarkingSC Please try to access the document and request access as I don't have your email address.

**Comment by SarahBousba2300** [comment]
@max3903 Hi i am new in odoo and i have to sell a service (rejection bills) as a product type service and invoice it, i found a several suggestions about using field service, how can i do it using this module! thank you

**Comment by max3903** [comment]
@SarahBousba2300 We, at Open Source Integrators, offer consulting services. Please contact us here: https://www.opensourceintegrators.com/contact
