### ISSUE TITLE
[14.0] Cannot create a Server Action that send an email everytime stages change

### ISSUE THREAD

**Issue by Jake-Tong-Epiklah** [OCA/field-service#1000]
## Module
Field Service - Server Action

## Describe the bug
I wanted to make a Server Action that will send an email to a customer and the workers involved that notifies the stage has changed from "New" to "Confirmed" but I setup the outgoing email server and the email template with the destination email is not wrong it still didn't send out any email. Is there something wrong with my setup?

## To Reproduce
**Affected versions**:

![image](https://user-images.githubusercontent.com/109071474/199874824-7058d41f-6416-487a-953d-8b484ea40c15.png)
![image](https://user-images.githubusercontent.com/109071474/199874866-c1a57c94-afb5-4c8b-9d56-4a13b9a4f53a.png)
![image](https://user-images.githubusercontent.com/109071474/199874894-e7a81534-0803-46cb-9489-617d0a09261c.png)
![image](https://user-images.githubusercontent.com/109071474/199874949-459e6896-d813-4399-bfab-5a0904f352bc.png)
![image](https://user-images.githubusercontent.com/109071474/199874978-ecd798c8-e339-4a93-a2d7-6ab4673666e5.png)

**Expected behavior**
I want an email to be sent to the Contact and the email of the workers involved in the order whenever I change the stage of the Order

**Comment by max3903** [comment]
@Jake-Tong-Epiklah Configuration looks good. Do you have the email in the queue? Can you provide the Odoo version?
