### ISSUE TITLE
[RFC] fieldservice_sale: alternative workflow fsm.order -> sale.order

### ISSUE THREAD

**Issue by HekkiMelody** [OCA/field-service#1027]
Hello,

I'm writing to gather potential comments about how best to go about a problem that I've encountered with the integration between fieldservice and the sales modules. I'd like to contribute some of my work back to the OCA if at all possible, but I'm unsure how to go about it.

I've installed the fieldservice modules for a few companies that broadly work on monitoring and maintenance of various types of machines and apparatuses, but this could also apply to your average electrician or plumber. In very broad strokes, the basic workflow involves:

1. Helpdesk.ticket (there is a problem)
2. FSM.Order (a technician is sent on-site to fix the problem)
3. Sale.Order and/or Account.Move (the technician invoices their work to the customer)

The first two parts work great with the modules as they currently exist, the third one not so much. Currently, if I understand it correctly, the `fieldservice_sale` module lets you create a FSM.Order from a Sale.Order, but not the opposite. This is fine e.g. if you're Ikea and you sell some furniture and also sell the service of having it assembled at the customer's.

Would the workflow I am proposing also be interesting and useful for other people? Would it be accepted as a module? Should I pitch a new module alternative to `fieldservice_sale`. or extend it?

Additions to this workflow that don't quite mesh well with what is already in the repo could be:

- logging inventory items "consumed" during the FSM.Order (e.g. spare parts used to replace a faulty one) for invoicing them to the customer later. You can't know what parts you're going to need until you actually are on site inspecting the machine
- mobile-friendly interface for closing a fsm.order while on-site
- automatically adding a line to the sale.order and/or account.move to invoice the time spent, based on the actual time spent recorded on the fsm.order
- same with distance traveled, in case of fsm.orders to distant locations
- marking teams as subcontractors (e.g. if the technicians you send on site are third party rather than your own employees) and automatically setting up a purchase.order to pay them for their time etc etc.

I already have made some of these modules and integrated these functionalities on my own in some private modules, they may need cleaning up to make them more generic and suited to OCA, and could also benefit from more community oversight.

**Comment by brian10048** [comment]
I agree we need to establish a way to create a sale order from a FSM order.  It's been requested here multiple times.

On a similar note, I started the draft PR #940 as a precursor to allowing to create a sale order from the FSM order.  I reworked the relationships between sale order and FSM order slightly and also simplified some of the code that is responsible to create FSM orders from the SO.  If you have any feedback for it, please let me know.

Given the changes in that PR, I think it will be easier to implement the feature to create the SO from the FSM Order.  My intent was to add the feature directly to the `fieldservice_sale` module.

I think all of your workflow additions sound very useful and would be accepted as individual modules here

**Comment by hparfr** [comment]
You can implement a part of this workflow with [stock_picking_invoicing](https://github.com/OCA/account-invoicing/tree/14.0/stock_picking_invoicing). It creates an invoice from a picking.

The need to create the picking first then sale/invoice is not reserved to fsm. You may want the same process for a repair order (RMA).

If you need to invoice different things (pickings, repair, fsm order) in the same order, I think about two alternatives:
- have an base object and keep references all the way down with hard links (database relation)
- create multiple invoices, group them with some soft links (txt reference) then merge all these invoices into one.

I prefer to keep the fieldservice_sale module to do one thing: generate fsm orders from a so.
May be we should rename this module: sale_fieldservice ? fieldservice_sale_generate_order ?

**Comment by max3903** [comment]
Hello @aleuffre 

I think your scenario is missing a step: if you are working on a problem and even decide to send someone on site to fix it, you must have some kind of obligation to do it. My guess is that your customer have signed a monitoring and maintenance contract, so there should be a sales order for that contract with a recurring invoice.

So when the FSM order is completed, based on the contract, you may invoice it or not. No need to create a sale order from the FSM order in this case.

```
logging inventory items "consumed" during the FSM.Order (e.g. spare parts used to replace a faulty one) for invoicing them to the customer later. You can't know what parts you're going to need until you actually are on site inspecting the machine
```
Already available.
```
mobile-friendly interface for closing a fsm.order while on-site
```
We have one that we provide to our customers. Please send an email to contact@opensourceintegrators.com if you are interested.

```
automatically adding a line to the sale.order and/or account.move to invoice the time spent, based on the actual time spent recorded on the fsm.order
```
Already available

```
same with distance traveled, in case of fsm.orders to distant locations
```
Good idea. We don't measure and keep the distance traveled yet.

```
marking teams as subcontractors (e.g. if the technicians you send on site are third party rather than your own employees) and automatically setting up a purchase.order to pay them for their time etc etc.
```
Already available.
