### ISSUE TITLE
[14.0][major-bug] Style in the settings page for user is lost after installation

### ISSUE THREAD

**Issue by marcos-mendez** [OCA/field-service#1065]
![Screenshot from 2023-04-05 11-43-08](https://user-images.githubusercontent.com/38361760/230120471-2770c3df-3481-4042-af6d-18646bce6c19.png)

SHOULD BE SHOWN LIKE THIS

![Screenshot from 2023-04-05 11-56-46](https://user-images.githubusercontent.com/38361760/230120624-e4f0d343-2128-416d-9e85-932b0289c92a.png)

**Comment by hparfr** [comment]
this is not related to fsm modules.
updating base module solves this issue.
