### ISSUE TITLE
[14.0] fieldservice: Tracking equipment movements using lots in Field Service during equipment swaps and repairs

### ISSUE THREAD

**Issue by rafnixg** [OCA/field-service#1070]
Hi, I am using the Field Service module (OCA) 14.0 and would like to know how I can track equipment movements between customers using lots, especially in a scenario where I need to swap an equipment for a customer and leave a backup equipment, while the original equipment is sent for repair and, subsequently, swapped back with the backup equipment once repaired.

I am aware that the Field Service module provides **fsm.location** for each customer and that there is also an associated **stock.location**. I would like to know how to utilize these locations and lots to achieve efficient tracking of equipment movements in this specific flow.

My current approach is as follows:

- Create a record in a custom model **stock.equipment.history**, which contains information about the equipment, lot, and origin and destination locations.
- Create a picking and internal movement based on the information from **stock.equipment.history** when swapping the equipment and placing the backup equipment.
- Record equipment movements during the repair process and the subsequent swap of the repaired equipment with the backup equipment.

However, I would like to get guidance on how to achieve this efficiently and if there is a better way to address this issue using existing functionalities in the Field Service module.

Thank you in advance.

**Comment by rafnixg** [comment]
@wtaferner @max3903 Do you have any idea?

**Comment by max3903** [comment]
@rafnixg 

With the current state of features, you would need to handle things manually:

- Create a first FSM order with the replacement equipment to do the 1st swap
- Create a repair order to fix the equipment
- Create a 2nd FSM order with the repaired equipment to do the final swap

As of now there is no way to automate this process. You would need to develop a new module to implement this.

**Comment by marcos-mendez** [comment]
In the case their is no replacement equipment @max3903 would, so basically there is the removal of the equipment repair and coming back of the equipment is this way easier or harder?

**Comment by max3903** [comment]
It's easier because there is less transaction/information to enter in Odoo.
