### ISSUE TITLE
[16.0] Calendar view in Service field order throws UncaughtPromiseError > OwlError

### ISSUE THREAD

**Issue by Albert-RC** [OCA/field-service#1110]
Calendar view throws an error when a worker is added in the filter and then selected. 

## Module
The name of the module that has a bug.
Field service base module

## Describe the bug
When I add a worker in the right side filter in calendar view, it throws an error and the calendar view becomes unusable. After, every time I change the view and go back to calendar view I get the same error without being able to change the filter that caused the problem in the first place.

## To Reproduce
Add a worker in the right side filter in calendar view. 

**Affected versions**:
For Odoo v16

1. Create a field service order and add a worker to the order. 
2. Go to calendar view
3. Add worker to calendar view (it crashes here)

**Expected behavior**
Worker is added in the filter and you can only see the orders that worker has assigned. 

**Additional context**
Error code:

OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    at handleError (https://netegesodoo.logicsolutions.es/web/assets/307-e737878/web.assets_common.min.js:1140:101)
    at owl.App.handleError (https://netegesodoo.logicsolutions.es/web/assets/307-e737878/web.assets_common.min.js:1970:29)
    at ComponentNode.initiateRender (https://netegesodoo.logicsolutions.es/web/assets/307-e737878/web.assets_common.min.js:1447:19)

Caused by: TypeError: Cannot read properties of undefined (reading 'type')
    at CalendarModel.makeFilterRecord (https://netegesodoo.logicsolutions.es/web/assets/365-bc69418/web.assets_backend.min.js:2595:324)
    at https://netegesodoo.logicsolutions.es/web/assets/365-bc69418/web.assets_backend.min.js:2585:470
    at Array.map (<anonymous>)
    at CalendarModel.loadFilterSection (https://netegesodoo.logicsolutions.es/web/assets/365-bc69418/web.assets_backend.min.js:2585:341)
    at async CalendarModel.loadFilters (https://netegesodoo.logicsolutions.es/web/assets/365-bc69418/web.assets_backend.min.js:2583:286)
    at async CalendarModel.updateData (https://netegesodoo.logicsolutions.es/web/assets/365-bc69418/web.assets_backend.min.js:2560:36)

**Comment by NICO-SOLUTIONS** [comment]
i can confirm this problem.  There are tow different types of erros. The one mentioend above and the follwing:

**Additional information!**
Error thrown after opening the calendar view and try to set the filter:

UncaughtPromiseError > TypeError
Uncaught Promise > field is undefined
TypeError: field is undefined
    makeFilterRecord@http://localhost:8069/web/assets/228-a98575d/web.assets_backend.min.js:2626:297
    loadFilterSection/filters<@http://localhost:8069/web/assets/228-a98575d/web.assets_backend.min.js:2616:470
    loadFilterSection@http://localhost:8069/web/assets/228-a98575d/web.assets_backend.min.js:2616:341

Error thrown after first opening the calendar view, opening calender view again:
UncaughtPromiseError > OwlError
Uncaught Promise > The following error occurred in onWillStart: "field is undefined"
OwlError: The following error occurred in onWillStart: "field is undefined"
    OwlError@http://localhost:8069/web/assets/209-3a2cc2f/web.assets_common.min.js:1240:1
    wrapError@http://localhost:8069/web/assets/209-3a2cc2f/web.assets_common.min.js:1600:77
    onWillStart@http://localhost:8069/web/assets/209-3a2cc2f/web.assets_common.min.js:1606:117
    useModel@http://localhost:8069/web/assets/228-a98575d/web.assets_backend.min.js:4823:12
    setup@http://localhost:8069/web/assets/228-a98575d/web.assets_backend.min.js:2519:214
    ComponentNode@http://localhost:8069/web/assets/209-3a2cc2f/web.assets_common.min.js:1558:202
    createComponent/<@http://localhost:8069/web/assets/209-3a2cc2f/web.assets_common.min.js:2096:6
    slot1@http://localhost:8069/web/assets/209-3a2cc2f/web.assets_common.min.js line 2056 > Function:15:36
    callSlot@http://localhost:8069/web/assets/209-3a2cc2f/web.assets_common.min.js:1665:25
    template@http://localhost:8069/web/assets/209-3a2cc2f/web.assets_common.min.js line 2056 > Function:8:12
    _render@http://localhost:8069/web/assets/209-3a2cc2f/web.assets_common.min.js:1496:96
    render@http://localhost:8069/web/assets/209-3a2cc2f/web.assets_common.min.js:1495:6
    initiateRender@http://localhost:8069/web/assets/209-3a2cc2f/web.assets_common.min.js:1563:47

Caused by: TypeError: field is undefined
    makeFilterRecord@http://localhost:8069/web/assets/228-a98575d/web.assets_backend.min.js:2626:297
    loadFilterSection/filters<@http://localhost:8069/web/assets/228-a98575d/web.assets_backend.min.js:2616:470
    loadFilterSection@http://localhost:8069/web/assets/228-a98575d/web.assets_backend.min.js:2616:341

Hope this helps. Will try to dig a bit deeper when time is availabe!

**Comment by brian10048** [comment]
Please check and review #1152  v16 and #1153 v17
