### ISSUE TITLE
install addons but no

### ISSUE THREAD

**Issue by julian560** [OCA/field-service#1117]
## Module
Field Service

## Describe the bug
I install addons but no fuction 

## To Reproduce
16.0

![image](https://github.com/OCA/field-service/assets/35088306/34e37701-82a2-4465-a1be-62b60abaf527)

![image](https://github.com/OCA/field-service/assets/35088306/96f1396b-645a-44cd-a1a2-da27591743cc)

**Comment by pedrobaeza** [comment]
Add your user to the corresponding security groups.
