### ISSUE TITLE
NEW ORDER - BACK BUTTON REQUIRED

### ISSUE THREAD

**Issue by xAlphaOmega** [OCA/field-service#112]
**Operations > Order > New Order**

The tabs in the top row (Request) (Inventory) ----(Others)
<img width="615" alt="field-service-toprow" src="https://user-images.githubusercontent.com/28748254/51548842-2c7dfe80-1e37-11e9-95c0-9f8cd4e05ab1.png">

If you click inventory tab you cannot go backwards in the menu items if you select this by mistake. 
<img width="1954" alt="field-service-inventory" src="https://user-images.githubusercontent.com/28748254/51548788-06585e80-1e37-11e9-98b6-af6ea8389a59.png">

This can be rectified by placing a back button here. 
<img width="1967" alt="field-service-backbutton" src="https://user-images.githubusercontent.com/28748254/51548792-08bab880-1e37-11e9-8cd4-7a92839c4ca6.png">

**Comment by max3903** [comment]
I can't reproduce this issue on Odoo Community or Enterprise. This looks like a limitation of your web customization...
