### ISSUE TITLE
[BUG] Order onchange Template

### ISSUE THREAD

**Issue by brian10048** [OCA/field-service#124]
Create a new Order.

Set the template.  Onchange method causes error:
  `File "/opt/odoo/field-service/fieldservice/models/fsm_order.py", line 249, in _onchange_template_id
    self.todo += (self.template_id.instructions + '\n')
TypeError: unsupported operand type(s) for +=: 'bool' and 'str'`

**Comment by brian10048** [comment]
The type error can be avoided, but still using the `+=` would result in appending multiple sets of instructions from different templates if an order template gets changed more than once.

**Comment by max3903** [comment]
@brian10048 Thank you for reporting. I believe it is fixed in the latest version. Can you try updating?

**Comment by bodedra** [comment]
Yes. it is fixed at https://github.com/OCA/field-service/commit/5acceed56e6430aa966fafece613234faeaee37d
