### ISSUE TITLE
[ADD] fieldservice_stock_location_builder

### ISSUE THREAD

**Issue by max3903** [OCA/field-service#129]
License: AGPL-3
Dependencies: fieldservice_location_builder, fieldservice_stock
Auto_install: True

# Module description

This module sets the inventory location on the sub-locations when running the location builder wizard.

# Usage

See https://github.com/OCA/field-service/tree/11.0/fieldservice_location_builder#id1

**Comment by bodedra** [comment]
@max3903 Usage link is dead.

**Comment by max3903** [comment]
@bodedra It is meant to point to this content: https://github.com/OCA/field-service/issues/128
