### ISSUE TITLE
[IMP] fieldservice - Order Report Action

### ISSUE THREAD

**Issue by brian10048** [OCA/field-service#144]
Fieldservice app does not currently provide a way to produce a printable report of a field service order. Companies will need to easily produce a report of one or multiple service orders for their customers.

### Usage
* Go to Operations > Orders
* Select multiple orders
* Click for action Print > Order Record
* PDF for selected orders is generated

### Technical Specifications
* [x] Add report (Print) action to field service order model
* [x] Add report template

@max3903 please review and edit specs if you have any suggestions. I can put something basic together pretty quick

**Comment by max3903** [comment]
@wolfhall Do you have some input on how the PDF should look like?
