### ISSUE TITLE
fieldservice: Admin user is not added to the FSM / Manager group

### ISSUE THREAD

**Issue by max3903** [OCA/field-service#180]
On version 12

* Install the Field Service module
* After install, Field Service does not appear in the main menu

**Comment by max3903** [comment]
The FSM dashboard does not show the stages:
![Screenshot from 2019-04-10 11-37-30](https://user-images.githubusercontent.com/939952/55896916-0f7ae100-5b85-11e9-9d2c-2df4dbc647a3.png)

**Comment by murtuzasaleh** [comment]
@max3903  #181
