### ISSUE TITLE
Code Error

### ISSUE THREAD

**Issue by elhamdaoui** [OCA/field-service#184]
Hi, 
did this code  worked for you ?!
I never saw it in odoo ORM !! Serach parameter must be a list of domaines.
 
    fsm_equipment = self.env['fsm.equipment'].search(
                'maintenance_equipment_id', '=', request.equipment_id)

**Comment by elhamdaoui** [comment]
In branch 11.0 there is many code errors.

**Comment by max3903** [comment]
@elhamdaoui Can you provide those code errors? and even provide a fix for some of them?

**Comment by elhamdaoui** [comment]
Hi @max3903 
Below some errors :
At 11.0/fieldservice_maintenance/models/maintenance.py:25

    fsm_equipment = self.env['fsm.equipment'].search(
            'maintenance_equipment_id', '=', request.equipment_id)
Must be (I think this error is solved)
    
    fsm_equipment = self.env['fsm.equipment'].search([
            'maintenance_equipment_id', '=', request.equipment_id.id)])

And at 11.0/fieldservice/models/fsm_order.py:174

            if vals['request_early'] is not False and\
                vals['scheduled_date_start'] is False:

must be replaced by

     if vals.get('request_early', False) and not vals.get('scheduled_date_start', False):

**Comment by brian10048** [comment]
Anything mentioned here has been resolved in 11.0 and 12.0
