### ISSUE TITLE
Improve README - what's "Field Service Management"?

### ISSUE THREAD

**Issue by petrus-v** [OCA/field-service#19]
Hi,

Thanks for all of that.

Could you add a topic about what's "Field Service Management" or link to a definition of what is it in the main README. It's probably obvious for you but was not 10 minutes ago for me !

Regards

**Comment by dreispt** [comment]
Sure, but also make sure you read the docs referred in #1

**Comment by pedrobaeza** [comment]
@petrus-v I'm curious why don't you and none of your team contribute to OCA now.

**Comment by petrus-v** [comment]
@dreispt, thanks for readme additions.

@pedrobaeza I've stopped to be part of odoo project at anybox for about 2 years (spending my all times on devops kind of things). I still follow some thread that get my curiosity and keep an eye of the whole great works done by the OCA.

Unfortunately I'm not the team... and I'm sad that no one from AnyBox get to the OCA code sprint at LLN. I believes on the community effort but probably Anybox needs some one to teach from outside why it's important for end costumers to do so and how to sell the time spend to the community.

Regards,
Pierre

**Comment by pedrobaeza** [comment]
Thanks for the frankness. We can speak about that if someone on your team wants and on OCA days there was a lot of this kind of discussion. It's a pity to lose you in OCA as very skilled people.
