### ISSUE TITLE
Checkbox to Streamline Field Service Worker Creation

### ISSUE THREAD

**Issue by xAlphaOmega** [OCA/field-service#190]
**New Request**

Create "Field Service Worker" Checkbox under employee. When box is checked the employee will appear in dropdown list to be imported as field worker. This would help streamline the process and make it more efficient. If there is a better way to impliment this feature than fantastic also.

### **ADD CHECKBOX TO EMPLOYEE TAB**

![Employee checkbox](https://user-images.githubusercontent.com/28748254/56475721-480a9c80-645a-11e9-99a8-eebc1c0ac6ea.png)

### **ADD BUTTON TO IMPORT EMPLOYEE INFO FS WORKER**
![employee import button](https://user-images.githubusercontent.com/28748254/56475720-480a9c80-645a-11e9-972e-4e82c26146f4.png)

**Comment by max3903** [comment]
Let's do a server action to convert employee(s) to Field Service worker. Like we did on a contact.
