### ISSUE TITLE
fieldservice_geoengine

### ISSUE THREAD

**Issue by max3903** [OCA/field-service#196]
- [x] FSM User group inherits Geoengine User
- [x] FSM Admin group inherits Geoengine Admin
- [x] The FSM Order map view is missing the vector layer: https://github.com/OCA/field-service/blob/11.0/fieldservice/views/fsm_order.xml#L406

**Comment by murtuzasaleh** [comment]
> * Geoengine Admin

@max3903 It means can I create Geoengine User and Geoengine Admin groups, Sorry can you please explain me?

**Comment by max3903** [comment]
Those groups are already created by the base_geoengine module. You just
need to add the inheritance so the FSM groups can use the mapping features.

**Comment by murtuzasaleh** [comment]
@max3903 Can you please close this issue.
