### ISSUE TITLE
fieldservice_maintenance

### ISSUE THREAD

**Issue by max3903** [OCA/field-service#197]
- [x] Creating a FSM Order of type "Maintenance" does not create a maintenance request

**Comment by murtuzasaleh** [comment]
@max3903 We missed one comment of previous closed PR, Can you please check this link. [fieldservice_maintenance](https://github.com/OCA/field-service/pull/176#issuecomment-480317666) 

Below is the error when I don't add this condition `if order.equipment_id and not order.equipment_id.is_fsm_equipment:`

![fieldservice_maintenance_issue](https://user-images.githubusercontent.com/20418904/56665697-29a9d880-66c8-11e9-86ed-90e8e7a71c9c.png)

**Comment by murtuzasaleh** [comment]
@max3903 Can you please check this [comment](https://github.com/OCA/field-service/issues/197#issuecomment-486250987) so we can complete this issue.

**Comment by max3903** [comment]
@murtuzasaleh Can we avoid this recursivity using the context?

When creating a fsm.order of type maintenance, create a maintenance request with `fsm_order = True` in the context.

When creating a maintenance request, if the equipment is an fsm equipment and `fsm_order = False` in the context, then create a `fsm.order`, otherwise don't.
