### ISSUE TITLE
Field Service Product

### ISSUE THREAD

**Issue by brian10048** [OCA/field-service#202]
## Improvements for fieldservice_sale (and fieldservice_purchase)

Companies need the ability to provide quotations for products that are provided via execution of a field service order.  Similarly, these products may need to be purchased from vendors via RFQ and purchase orders.

### Requirements
Extend `product.template` with relationship to FSM order template
Confirmation of sale order (purchase order) creates a field service order for each SO (PO) line based on that product's related FSM order template

### Technical Specifications
@max3903 - looking for your input here and I will be glad to work on this:

_Should we add a new option "Field Service" for the selection field `type` on `product.template`? There is already an option for "Service", but it tends to be used more for Project related work._

_Should this be a separate module fieldservice_product? or part of fieldservice_sale?_

_Feel free to edit this and add specs as needed_

**Comment by max3903** [comment]
# fieldservice_sale

I would not change the `type` on product.template.

On the Sales tab of the product, I would add:

* the option to create a Field Service Order (like the different options with Project: create a task, create a project, etc)
* the option to select a FS Order template or a FS Recurring Order

# fieldservice_purchase

I would replace the request workers field on fsm.order by a list of purchase quotations/orders. We can achieve the same feature by selecting to create a purchase tender and show the quotation on the FS order.

If the route MTO is selected, then a FS order would create a purchase tender (and purchase quotations for the same workers as we would put in request workers) or one purchase quotation for the first worker in product.supplierinfo who serves the territory of the order.

CC: @wolfhall

**Comment by brian10048** [comment]
Sounds good.  I will work on sale first
