### ISSUE TITLE
TypeError: Model 'fsm.category' does not exist in registry.

### ISSUE THREAD

**Issue by Selectsolution** [OCA/field-service#205]
module: fieldservice_skill
version: 11.0

**Steps to reproduce**
- ...

**Current behavior**

**Expected behavior**

**Comment by bodedra** [comment]
IMO It's invalid. Please try with updated code. 

fieldservice_skill is depend on fieldservice module.

fieldservice module has declared fsm.category object. Here is reference: https://github.com/OCA/field-service/blob/11.0/fieldservice/models/fsm_category.py#L8

**Comment by bodedra** [comment]
@max3903 Seems we may close these.
