### ISSUE TITLE
Field Service functionalities for "informal" relation with customers

### ISSUE THREAD

**Issue by rdc02271** [OCA/field-service#218]
Hello,

Warning: I am newbie to the Odoo / python worlds.

In my opinion the field service world is divided in two groups: the formal and the informal.
In the formal group, field service companies have contracts with their customers (usually companies) that specify what equipment will be serviced, how long it should take (Service level agreement), labour costs,etc.

In the informal group, field service companies have no contracts with their customers because these customers are usually end users.

Imagine your washing machine broke down: do you have a contract with a field service company?Not usually, right?  
 You just call some company and ask them to swing by and solve the problem.
This is why I call this an "informal" relationship. There are no contracts, no service level agreements, no knowledge of what equipment the customer has.

So, I am trying to change the Field Service Order user interface to display the full equipment data but without sucesss so far.
Right now, the original form only displays the equipment Name.
That is not enough for the technician and the dispatcher.
Basic information like Equipment Category, Model, Serial Number and others should be displayed on the Field Service Order form.

How can I display that data?

I am using the runbot service to test the changes...

http://3369754-12-0-939b7e.runbot2-2.odoo-community.org/web?debug=1#id=1&action=460&model=fsm.order&view_type=form&menu_id=317

http://3369754-12-0-939b7e.runbot2-2.odoo-community.org/web?debug=1#id=2&action=468&model=fsm.equipment&view_type=form&menu_id=317

Thank you,
Jorge

**Comment by max3903** [comment]
Hello @rdc02271,

Thank you for your explanation. Assuming you are in the informal world, as you said you have no info of the equipment, so why do you want to show information you don't have?

To answer your technical question, you can have related fields on the order to display information of the equipment:
https://www.odoo.com/documentation/12.0/reference/orm.html#related-fields

**Comment by rdc02271** [comment]
Dear Sir,
Thank you for replying.
Yes, as you have said when we get the call we don't have the equipment data. But the customer will tell us basic information like "Equipment Type: Washing Machine, Dishwasher, Home Cinema, HVAC" , "Manufacturer" and sometimes ( if we are lucky ) the "Model" and "Serial Number".

So you ask, what is your goal ?
Simple, speed up data entry for equipments.

1) I don't want the field technicians  to open up the work order and then open the equipment form to fill out the rest of the data, then go back to the work order and assign that new equipment to the work order.

2) It really is useful for the technician to see right there in work order the equipment data. 

Please take a look at some photos of our current software and you will see what I mean.
http://www.msm-software.com/html/pantalla_elite.html

Thank you for your help and attention,
Jorge

**Comment by rdc02271** [comment]
Hello again,
I forgot to mention one key point: my end goal is to edit in place the equipment data, right there in the work order form.

Also, should I post these questions here or somewhere else ?

Thank you,
Jorge C.

**Comment by rdc02271** [comment]
Hello again,

Please, allow to talk about our company works.
We are a retail store/repair worksho that sells and repairs electronic equipment: Ar conditioners (HVAC),  led televisions, induction cooktops, home cinema, kitchen hoods, etc.

We have technicians working full time at the workshop (they never leave the workshop) and we also have  field technicians doing installations and repair work at our customers sites.

How do our customers get in touch with us : 
1) By phone: they call us asking saying that an equipment that is not working properly.
2) They show up at our store/workshop with the broken equipment (small devices, of course, like smart phones, video camera, led televisions, stuff like that).

Thank you,
Jorge C.

**Comment by max3903** [comment]
@rdc02271 I would create:

* a wizard with fields for all the info you can get. Upon saving, the info would be stored in the different models (order, equipment, location, etc). Next screen you show to the user is the form of the created order. No need for related fields to the equipment on the order.

* a menu item to call the previous wizard
