### ISSUE TITLE
Order  : Description value is deleted everytime we change the location field.

### ISSUE THREAD

**Issue by rdc02271** [OCA/field-service#220]
Hello,

Steps to reproduce problem:
1) Create a new Field Service Order
2) Write something in the Description field (fsm.order.description)
3) Select a Location (fsm.order.location_id)
4) The Description content disappears.

Thank you,
Jorge C

**Comment by rdc02271** [comment]
Hello,
Just to confirm: the fsm.order.description is the field where we should write the malfunction of the equipment, correct? We would write on this field the problem description, something like, "The oven doesn't heat up". Right?

I am asking this because I was looking at the https://github.com/OCA/field-service/blob/12.0/fieldservice/models/fsm_order.py when I noticed the "Description" field is being cleared everytime the method "copy_notes" is called.

Shouldn't that method change some other field? 
In my opinion the field "Description" should be used solely to write down the problem.

Thank you,
Jorge

**Comment by max3903** [comment]
Ping @patrickrwilson

**Comment by patrickrwilson** [comment]
I believe the on-change event on the location field is overwriting the description with the directions from the location when the location changes. The original thought behind this is that each location may have specific directions the field worker follows each time a order is created for that location (could contain things like "Needs 24hr notice before entering" or "Front Gate Pin: 1234"). I agree that the description is probably not where this information should be set.

Suggested Improvement: Add a field called location_directions and place it just above the instructions field in the instructions tab. Then this new field is what gets updated when the location changes and the description isn't touched, using the on-change event.

**Comment by wolfhall** [comment]
I like the idea to display location instructions on the order in addition to the order instructions. 
I would probably post it below the order instructions, if few locations have instructions and above if most locations have a description.
