### ISSUE TITLE
Question: Why aren't the Workers/Technicians not Partners/Employees ?

### ISSUE THREAD

**Issue by rdc02271** [OCA/field-service#242]
Hello,

One quick question:

Why aren't the Workers/Technicians a  Partner/Employee?
How will you keep track of employee work hours? Timesheets?
Isn't that repetitive and a bit confusing.

When we create a Work Order and then confirm it we must specify the "Assigned to" field. In theory this would be a technician/worker which is different from an Employee/Partner.
Thus we have to create and maintain two records for the same person: techician (worker) and Employee/Partner...

The list of "Request Workers" are also "Contacts" instead of being Employees/Partners...

Shouldn't Employees be a form of Partners just like Customer and Vendors?

I am asking this because it would be useful to link "Work Order Schedule" to the Employee Calender/Google Calendar...

Thank you,
Jorge C

**Comment by wolfhall** [comment]
Jorge,
Workers are derived from Partners, so there is a relationship.  but they have many additional attributes that are specific and are not needed on all partner records.  That's why we have a separate entity.
For employees we use timesheets.  for contractors we can use start and end time on jobs.
A FSM person has a matching partner record.  so you don't have to keep track separately.
Requested workers are not contacts but FSM workers.
We also have workers that are not employees.

**Comment by rdc02271** [comment]
Hello,
Thank you mr. Wolfhall for the explanation. Things are clear now.

Two questions:

1)Is there any plans to allow the user to specify that a FSM worker is also an employee?
At this moment we are unable to link the FSM worker to the Employee record.

2) By default whenever we create a FSM worker the flag res.partner.customer is set to TRUE.
Is there any specific reason to do this?

Thank you,
Jorge

**Comment by dreispt** [comment]
I see relevant being able to use Timesheets for external Workers, even if for that "dummy" employees need to be created.

I've seen Worker teams having both employees and contractors, and in this case we would like our business process to be the same regardless of the "type" of worker,

**Comment by wolfhall** [comment]
Daniel is right, we should have separate timesheets for non-employee workers. 
To Jorge's questions:
1) currently the FSM worker record is tied to the partner record which indicates 1099 (contractor).  if it is not a 1099, then it should be an employee.  But I don't think this is enforced.  We could improve this a bit and do some of these changes:
a) allow partner record to be opened directly from FSM worker
b) add "Is contractor to FSM worker form (if 1099 was checked)
c) we are currently using tags on the partner record to show employee versus contractor.  we could display this on the FSM form.
2) I have no idea why we would set this to customer.  It may have been a mistake - when we create FSM locations we set them to customer, but for workers this should be optional.

**Comment by max3903** [comment]
@wolfhall 1099 is US-specific. We want to use the "Is a Vendor" checkbox...

**Comment by wolfhall** [comment]
@max3903 agreed

**Comment by KJAgit** [comment]
Hi,
Is there any way you could have the option to create a FSM Worker from an EXISTING Partner OR create a new partner?
The check boxes for "Is a FS Worker" are there under an existing partner, but are disabled.

**Comment by wolfhall** [comment]
Yes, it is not very intuitive, but you can convert a partner record to FSM Worker by using the action "convert to FSM record"
Then pick "worker" as the record type.
It would be nice to convert a partner to FSM worker or location by simply clicking the checkbox.

**Comment by babatoko** [comment]
Hi @Wofhall,

I still don't understand why workers are derivated partner  instead of employe.

Would you clarify please?

**Comment by brian10048** [comment]
@babatoko In many field service companies the worker is not always an employee.  A company may hire a vendor to perform the field service work.  This vendor is not a direct employee of the company.  The vendor may be another company altogether and therefore needs to be derived from the partner model

**Comment by wolfhall** [comment]
@babatoko - Brian has the right answer - I also pointed this out in the posts above.  We have mobile workers who may or may not be employees.  We are also soon releasing a non-OCA mobile app to allow field services mobile access for Odoo users.

**Comment by babatoko** [comment]
@wolfhall, thanks for replying,

In other hands, how do you manage worked time against planned time?

Would it be possible to track time on each work order, by customer and so on.

You referre to a mobile app, would it be possible to be beta tester?

**Comment by wolfhall** [comment]
@babatoko Each order has a duration for planned time.  Also, each order has a actual start and end time and duration (under the execution tab).  With these values a comparison is easy.

**Comment by babatoko** [comment]
@wolfhall

How do we do to manage a work order with have to be .are by 2 or more employees. How workers record their worked time against the work order?

Currently, in my company we use timesheet to record all worked time against project task and reuse pivot report from timesheet, attendance and project. 

A project in my case, should be substiued by contract or agreement module.

**Comment by wolfhall** [comment]
@babatoko  Currently we can only assign a single worker to a Service order.  But multiple techs can log time to the order.  
On the Order form we have an accounting tab that links to the employee timesheet.  anybody can log hours here, including multiple workers.

**Comment by teicom** [comment]
I just installed the module and I find it really interesting but I don’t find it logical to have to write the names of workers again, either employee or partner, should be able to be selected from the Contacts module, like selecting a client.

**Comment by max3903** [comment]
@teicom On a contact (employee or partner), you can convert the record to a FSM worker or to a FSM location. In the action menu on top of the form view, you should find the option "Convert to a FSM record".

We use the same logic as partner / user, because not every partner is a FSM record.

**Comment by teicom** [comment]
> @teicom On a contact (employee or partner), you can convert the record to a FSM worker or to a FSM location. In the action menu on top of the form view, you should find the option "Convert to a FSM record".
> 
> We use the same logic as partner / user, because not every partner is a FSM record.

Great!
