### ISSUE TITLE
Question about status of this project, how about adding test script?

### ISSUE THREAD

**Issue by kittiu** [OCA/field-service#252]
Hi all, cc @max3903 

Sorry for the mixed question. I am interested in this project, and want to help out in some way. When I start to migrate module "fieldservice_recurring", but notice that most modules has no test script, and so, with zero knowledge in this field it is hard to do migration.

I wonder if it is a good idea for your team if I start by adding test scripts and/or README to learn more about functionality. But that would need your team guideline, i..e, tell me the right use cases and user steps...

May be I can summarize as questions here,
1. Is the functionality of this project mature? Work done in real customer projects?
2. Any resources that can help me understand this field-service better?
3. Is it good idea to start contribute by adding test scripts?

Thank you.

**Comment by max3903** [comment]
@kittiu 

You will find some documentation here #1.

Adding tests would be a great contribution and allow us to raise the development status from beta to stable.

1. Yes and yes. We are starting to implement those modules for different customers without any changes.
2. You can count on @wolfhall, @osi-scampbell and @max3903 to the extent limited by our schedule. I can't speak for @brian10048 .
3. Yes! @osi-scampbell and I can review them.

Thank you for joining.

**Comment by brian10048** [comment]
I can help answer questions and improve the README documentation.  This should help @kittiu in writing the test scripts.  

Some demo data would also be a good addition related to this cause.

**Comment by kittiu** [comment]
Hi everyone,

Thanks for the kind response. @brian10048 I can focus on the fieldservice_recurring first, if you could add more detailed steps in readme, that would be great. But not to worry, I would also read through the code and ask more questions if I don't understand. ;)

**Comment by kittiu** [comment]
Hi everyone,

As @brian10048 mentioned about data. I do agree, as fieldservice (base) seem to relate to many master data. May I ask if it is possible for me to get some good master data (I also not sure what will make sense), may be as .csv or .xml, or even database with removed transaction.

But if not possible, I can also create some fake data, i.e., Territory 1, Territory 2, etc to work with.

If we can have the good data, it is great, if not no problem.

Thanks

**Comment by kittiu** [comment]
Hi, given the above question still valid. I just continue working on https://github.com/OCA/field-service/pull/257
I am adding test for fsm_equipment,
- What are the good sample of equipment's stage ?
- Should it be data like in order's stage, or it should be demo only ?

**Comment by brian10048** [comment]
@kittiu @max3903 
Can we close this issue and continue tracking progress in #278?

**Comment by max3903** [comment]
:+1:

**Comment by kittiu** [comment]
Yes and sorry of not having time to follow up.

**Comment by brian10048** [comment]
Not a problem @kittiu. Thanks for the work you have done here.  We welcome it anytime
