### ISSUE TITLE
[12.0][BUG] Method not used, self.env['fsm.person].get_person_information(vals) ?

### ISSUE THREAD

**Issue by kittiu** [OCA/field-service#264]
I see the method is not being called. And also param vals is not being used in the method.
Is this method still valid?

**Comment by brian10048** [comment]
It looks like it is used in the javascript here.  

https://github.com/OCA/field-service/blob/685ad65ee5b5bf8e7511e0d9dbaf05da0db06e98/fieldservice/static/src/js/fsm_gantt.js#L41

I believe @smangukiya is familiar with this

**Comment by smangukiya** [comment]
@kittiu @brian10048 Thank you for your input on this.
Yes, 'get_person_information' method is getting called from Javascript to get person information in structured form of dictionary and it is useful in fsm_gantt.js for further processing.

I hope it helps to understand it more.
Thanks

**Comment by kittiu** [comment]
Thank you all. So I may close this.
