### ISSUE TITLE
[12.0][BUG] fieldservice_account, error when create new Work Order

### ISSUE THREAD

**Issue by kittiu** [OCA/field-service#271]
**Steps:**

- Install fieldservice_account
- Create new work order without selecting Bill To
- Error

**Note:** This problem only occur if bill_to is using widget="radio". Not sure it is a core Odoo bug or not.

![Selection_143](https://user-images.githubusercontent.com/1973598/60765092-c8868400-a0be-11e9-99d1-2026567b864b.png)

**Comment by max3903** [comment]
@kittiu Please update your code. I believe it has been fixed with a default value.

**Comment by kittiu** [comment]
Thank you
