### ISSUE TITLE
[12.0] Add Test Scripts

### ISSUE THREAD

**Issue by kittiu** [OCA/field-service#278]
Keep track of fieldservice modules' test scripts.

[12.0 Coverage](https://codecov.io/gh/OCA/field-service/branch/12.0)

- [X] fieldservice @kittiu https://github.com/OCA/field-service/pull/257
- [X] fieldservice_account @kittiu https://github.com/OCA/field-service/pull/273
- [ ] fieldservice_account_analytic
- [ ] fieldservice_account_payment
- [x] fieldservice_activity
- [X] fieldservice_agreement @kittiu https://github.com/OCA/field-service/pull/303
- [ ] fieldservice_change_management
- [ ] fieldservice_crm
- [ ] fieldservice_delivery @kongrattapong https://github.com/OCA/field-service/pull/291
- [ ] fieldservice_distribution
- [ ] fieldservice_fleet
- [ ] fieldservice_geoengine
- [ ] fieldservice_google_map
- [ ] fieldservice_google_marker_icon_picker
- [ ] fieldservice_isp_account
- [ ] fieldservice_isp_flow
- [ ] fieldservice_location_builder
- [ ] fieldservice_maintenance #661 
- [ ] fieldservice_partner_multi_relation
- [ ] fieldservice_project
- [ ] fieldservice_purchase @kongrattapong
- [X] fieldservice_recurring @kittiu https://github.com/OCA/field-service/pull/251
- [ ] fieldservice_repair
- [ ] fieldservice_route
- [ ] fieldservice_route_account
- [ ] fieldservice_route_stock
- [ ] fieldservice_route_vehicle
- [x] fieldservice_sale @brian10048 https://github.com/OCA/field-service/pull/486
- [x] fieldservice_sale_recurring
- [ ] fieldservice_sale_stock
- [ ] fieldservice_skill
- [ ] fieldservice_stage_server_action
- [ ] fieldservice_stage_validation
- [ ] fieldservice_stock
- [ ] fieldservice_stock_account
- [ ] fieldservice_stock_account_analytic
- [ ] fieldservice_substatus
- [ ] fieldservice_vehicle
- [ ] fieldservice_vehicle_stock

**Comment by brian10048** [comment]
@max3903 How does it work to setup the coverage checks now that tests are being worked on?

**Comment by max3903** [comment]
@brian10048 This is automated here:
https://github.com/OCA/field-service/blob/12.0/.travis.yml#L42
and there:
https://github.com/OCA/maintainer-quality-tools/blob/master/travis/travis_after_tests_success
