### ISSUE TITLE
Module field service not installing

### ISSUE THREAD

**Issue by sbinmahfooz** [OCA/field-service#279]
Hi, I have installed all prerequisites, etc.. the field service module still not installed with a message 'Cancel Install'

**Comment by kittiu** [comment]
I installed without problem. Can you explain what you did in derailed steps and may be attach piccture of error

**Comment by sbinmahfooz** [comment]
Hi Kittiu, ihave used the sudo getw command do download from App Store, unzipped it, then installed it
![image](https://user-images.githubusercontent.com/52846567/61180010-9e314b00-a617-11e9-8d63-c181a1e3aaed.png)

there is no specific error, only not installed and no views or menus created

**Comment by max3903** [comment]
@sbinmahfooz Can you provide the Odoo log file when you install fieldservice?

**Comment by sbinmahfooz** [comment]
Sorry, how to get the log file?

**Comment by sbinmahfooz** [comment]
resolved, thanks, I have uninstalled, deleted and installed the module and the dependencies, the issue was I believe in web timeline and partnerfax
