### ISSUE TITLE
Field Service Business Case

### ISSUE THREAD

**Issue by sbinmahfooz** [OCA/field-service#281]
module: fieldservice
version: 12.0
Hi, i wanted to check the applicability of a business case using the FSM app, since i am new to it. 
Objective of the Business Case: is to facilitate the deliveries of the products i produce on daily basis to the customers in different location. with features like customer notification, route optimimzation, planning, etc... 
i believe the system encompas most of the requiered features, however, not sure how to start
**Steps to reproduce**
- SALES ORDER CONFIRMED: 
- DELIVERY DATE and TIME ASSIGNED to SALES ORDER.
- PRODUCTS ARE PRODUCED AND READY TO LEAVE THE FACTORY
- DRIVERES ASSIGNED BASED ON RULES
- CUSTOMERS RECEIVE NOTIFICATION OF DISPATCH
- CUSTOMER RECEIVE PRODUCT AND CONFIRM RECIEVAL in FULL OR PARTIAL
- SYSTEM UPDATE INVOICES BASED ON DELIVERED QUANTITIES AND INVOICES AUTOMATICALLY VALIDATED AND CREATED
this at high level, the question is, is the FSM the best solution (with customization if required) to my business case
regards

**Current behavior**

**Expected behavior**

**Comment by wolfhall** [comment]
@sbinmahfooz 
The FSM module does most of these items, but we have not implemented the rules-based assignments yet.  that is coming later this year.  But the user can see skill levels and requirements for delivery (e.g. needs a forklift) apply rules.  
Customers receiving product can be done via e-signature.
We also offer a mobile tool (not in OCA) to help with order management and signature at a customer.

**Comment by sbinmahfooz** [comment]
@wolfhall Thanks for the input, I will work something and once ready will develop the business case and share
