### ISSUE TITLE
[12.0] Remove stage logic from fieldservice.fsm_order

### ISSUE THREAD

**Issue by hparfr** [OCA/field-service#309]
In v12, stages are rigid and logic is hardcoded in the main module (fieldservice). It leave fieldservice not generic enough.

I see a migration path to a cleaner module in two steps:

 -1) Decouple: move the actual code in a new module like fieldservice_default_workflow. 

 -2) Improve: change the design to allow flexible workflows, add optional stages, support different teams, and configurable logic.

Because 2) is hard, it can be done later.

Before working on the matter, do you agree to remove all the stage logic from fieldservice module ?

**Comment by hparfr** [comment]
@max3903 @dreispt @brian10048

**Comment by max3903** [comment]
Ping @wolfhall

**Comment by max3903** [comment]
@hparfr Can you provide more information about your situation and workflow?

**Comment by hparfr** [comment]
My clients work in :
- maintenance of fleets of vehicles
- building / industrial cleaning 
- caretaker
- surveillance
- other B2B services.

UC 1): 
The company has only one specialized truck and one driver. There is no need to have to "assign" the workorder to this guy since the information can be deduced from other fields.

UC 2):
The order are scheduled during the sale, so there is no need to have a "scheduled" stage.

UC 3):
The requested stage can be useless if the assignation is not necessary (cf UC1) or imposed by a manager.

UC 4): Resolution note can be useless. (like cleaning the floors)

UC 5): time sheets of employees are not necessary when employees have fixed time contracts or when their presence is assessed by another system (or not tracked at all).

UC 6): "enroute" granularity is overkill for my clients

UC 7): "Actual End" time is not tracked by my clients. They will never have need nor the maturity to do something from it.

The conditions before changing to another stage I need are:
- request client satisfaction (only for some workflows and with random selection)
- client signature (only for some workflows)
- some approbation workflow before putting in confirm.

I may need new stages like Dispute, to be Rescheduled...

**Comment by wolfhall** [comment]
@hparfr,
You are right that the current logic does not work in all cases.  It was designed to match the majority of use cases we encountered.

I like the idea to make this more flexible and integrate a rules engine that allows the free definition of stages and conditions to move from one stage to the next. 

Let me think about this.   We just need to make sure we don't break existing functions since this is used daily by a large number of users.

**Comment by wolfhall** [comment]
Some of your very simple workflows may also be covered by the new Odoo Field Service functions

**Comment by hparfr** [comment]
Step 1 is done in #334 and #333 
I've just moved stages to another module.
