### ISSUE TITLE
Outbound / Inbound Transfer boxes

### ISSUE THREAD

**Issue by DatenSAS** [OCA/field-service#311]
Hi,

In a Odoo.sh V12 installation, I'm not able to find the boxes that are referred in the configuration instructions from the App Field Service - Stock 

- Check the box ‘FSM Order Line’ for outbound transfer
- Check the box ‘FSM Return Line’ for inbound transfer

**Comment by brian10048** [comment]
@DatenSAS I believe the problem is that the readme instructions need to be updated

**Comment by RevianBudiman** [comment]
> Hi,
> 
> In a Odoo.sh V12 installation, I'm not able to find the boxes that are referred in the configuration instructions from the App Field Service - Stock
> 
> * Check the box ‘FSM Order Line’ for outbound transfer
> * Check the box ‘FSM Return Line’ for inbound transfer

hy

**Comment by RevianBudiman** [comment]
i

> Hi,
> 
> In a Odoo.sh V12 installation, I'm not able to find the boxes that are referred in the configuration instructions from the App Field Service - Stock
> 
> * Check the box ‘FSM Order Line’ for outbound transfer
> * Check the box ‘FSM Return Line’ for inbound transfer

facing the same problem, need help
