### ISSUE TITLE
[12.0] fieldservice_recurring don't create order on confirm

### ISSUE THREAD

**Issue by hparfr** [OCA/field-service#312]
I guess it's the same for previous versions, but.

Create a frequency like : Every Monday, weekly.
Create a recurring order with this frequency on Friday, and confirm it. 
An order will be created on Friday (datetime.now()).

The date of this order is not compliant with the frequency defined.

I suggest to remove _create_order from action_start and let the cron create the orders.

```py
    def action_start(self):
        for rec in self:
            if not rec.start_date:
                rec.start_date = datetime.now()
            rec._create_order(date=rec.start_date)
            rec.write({'state': 'progress'}
```
https://github.com/OCA/field-service/blob/12.0/fieldservice_recurring/models/fsm_recurring.py#L101

**Comment by brian10048** [comment]
@hparfr I agree this is an issue.

Could we improve it so that the first order is still created, but with a date that is compliant?

**Comment by hparfr** [comment]
Why create only one order ?

**Comment by brian10048** [comment]
I don't see a problem creating all the orders
