### ISSUE TITLE
Clarify location hierarchy with service points

### ISSUE THREAD

**Issue by brian10048** [OCA/field-service#32]
In #27 a `location` model was introduced, but it is similarly named to `fsm_location` which can be somewhat confusing as to its purpose.

I propose `fsm_service_point` instead to create a hierarchy of locations/areas/items to be tracked within an overall `fsm_location`

The `fsm_service_points` would also be related to a specific `fsm_service_point_type` to help create a hierarchical categorization of `fsm_service_points`

**Comment by dreispt** [comment]
Any reason for the "service points" to not be the lower layer of the FSM Location tree?

**Comment by brian10048** [comment]
I don't completely understand the question.  Are you suggesting just creating a hierarchy of the FSM Location model rather than having a separate model of Service Points?

**Comment by brian10048** [comment]
To further expand on the concept of this issue

Using the example described in the Use Cases spreadsheet from #1 labeled Inspection in the Industry column:

The `fsm_service_point` would represent the components of a fire system needing inspected.  Maybe there are `fsm_service_point_types` named "Controller", "Zone", "Sensor" for a fire system.  Sensor is a child of Zone which is a child of Controller.  There may be multiple Controllers within a `fsm_location`

The `fsm_service_point_type` would help to configure the checklist of inspection items/activities that need performed and values recorded unique to that specific `fsm_service_point_type`
