### ISSUE TITLE
Field Service Conditions

### ISSUE THREAD

**Issue by brian10048** [OCA/field-service#332]
In my field service company we track what we call "Conditions" which can be described as a standardized list of various situations that may be encountered while performing a field service.  

These may be reported by the customer and recorded in the service request phase in order to better help the worker understand what needs to be resolved from the customer point of view.  Conditions are also recorded by the worker during the resolution phase based on what was actually observed by the worker.  

Conditions can be helpful to streamline data entry.  Also, they are valuable for historical purposes and allow us to notice common problems (maybe with a location or a worker).  We also use certain conditions to trigger other actions whether that action is a follow up service order, sales opportunity, phone call, etc

I can submit a PR for this, but would like to gather some feedback before I work on it.  

Should this be a separate module? Or is it generic enough to fit into base field service with an option to enable its views/usage in a security group?

I am open to suggestions on naming, etc

Basic plan to include:

New model `fsm.conditon` with 
- char field Name
- text field Description

Extend `fsm.order`
- Many2many field for customer_condition_ids visible under 'Request' tab
- Many2many field for worker_condition_ids visible under 'Resolution' tab

Further improvements could include general reporting features and server actions tied to conditions recorded

@max3903 @wolfhall

**Comment by max3903** [comment]
@brian10048 Can you provide examples of conditions and their impact please?

**Comment by brian10048** [comment]
These are specific to my industry. We provide lawn care services.

Customer may report a condition "Brown Spots" or "Weeds" that needs addressed.

The worker will visit the location to provide a service and report conditions noticed while on the property.  The worker may also report "Weeds" as a condition.   Additionally, the worker may notice other conditions which are not in the scope of the current service.  For example, a worker performing a lawn treatment may notice the condition "Irrigation Problem" which is not in the scope of work for this service order or worker.  A server action would be tied to "Irrigation Problem" which might create another service order for an irrigation worker.

**Comment by wolfhall** [comment]
@brian10048 @max3903 
I think it makes sense to offer this type of "condition",  "issue", "service", "need", or "observation"
I struggle with a good neutral word for this.  Maybe the label is specific to the type of service and needs to be configurable as well (by an admin) 
The module could be fsm.condition as described.
I can see this also extend to the mobile unit and used for reporting.  An order can have a number of these "conditions".

**Comment by brian10048** [comment]
@wolfhall @max3903 

I've been thinking about this further and with reference to issue #20- items 2 (different activities or processes for different request types), 3 (activity type, check list, values recorded), & 4 (feedback for next visit, create sales action or restocking order)

What if we had a configurable FSM Activity or Task?  Sequences of activities/tasks could be specified on the FSM order template.  Or added manually to orders without templates.

An activity can be configured to have:
 - a value input as a result
 - select one "condition" from a list of many
 - select multiple "conditions" from a list of many

A worker is required to perform each activity in sequence and the result is recorded as a condition (for lack of a better term. Maybe "outcome" or "result" works best here).  

This makes worker instruction and worker reporting (especially via mobile) highly configurable and clearly defined based on the order template.

**Comment by wolfhall** [comment]
My original design actually had Activities in addition to Orders to break Orders down into multiple "tasks" or "activities" 
![image](https://user-images.githubusercontent.com/3019378/64637367-76acf380-d3b8-11e9-9047-0fe3e157b69b.png)
We skipped it for now but I know that people need the ability to define multiple tasks on a work order.

**Comment by hparfr** [comment]
It can be in another module since not every one need this granularity.

I know some company work with a concept of checklist ("do I have my security shoes?", "am I certified for this work", etc. before starting the order), I don't know how it fit with your needs.
