### ISSUE TITLE
[ADD] fieldservice_fleet

### ISSUE THREAD

**Issue by max3903** [OCA/field-service#343]
This module allows you to link the vehicles and workers of Field Service with vehicles and drivers of Fleet.

Beware that the Fleet module can have more vehicles than the FSM one (not all vehicles of the company are used for Field Service work).

# Configuration

* Go to Fleet
* Review the vehicles created during the installation from the Field Service vehicles

# Usage

## Fleet

* Go to Fleet
* Create or select a vehicle
* Check the box "Is used for Field Service" to create the Field Service vehicle

## Field Service

* Go to Field Service > Master Data > Workers
* Select or create a worker
* Go to Field Service > Master Data > Vehicles
* Select or create a vehicle and assign it to a worker

# Technical Specifications

## res.config.settings

- [x] Add the option "Link to Fleet Vehicles" (module_fieldservice_fleet) in the fieldservice module to install this module (in the Vehicles section)

## fsm.vehicle

- [x] Add a many2one field "Vehicle Details" (fleet_vehicle_id)
- [x] Set fsm.vehicle to inherit from fleet.vehicle based on the fleet_vehicle_id field
- [x] Add a unique constraint on (id, fleet_vehicle_id) to have only one FSM vehicle linked to a Fleet vehicle
- [x] Extend the write method to update the driver of the fleet.vehicle based on the worker of the fsm.vehicle

## fleet.vehicle

- [x] Add a boolean field "Is used for Field Service" (is_fsm_vehicle)
- [ ] Add an onchange method onchange_is_fsm_vehicle:
* if is_fsm_vehicle is true:
  * Create a fsm.vehicle linked to the fleet.vehicle
  * If the driver is set
    * If the driver is linked to a fsm.worker, assign it to the fsm.vehicle
    * otherwise create the fsm.worker and assign it to the fsm.vehicle
* otherwise
  * if there is a fsm.vehicle linked to the fleet.vehicle, archive the fsm.vehicle

## Migration

- [x] Provide the migration script to create the fleet.vehicle from the existing fsm.vehhicle and link them together. Fill in as much field as we can on the fleet.vehicle.

**Comment by brian10048** [comment]
@max3903 I can work on this if no one on your team is already doing so

**Comment by max3903** [comment]
@brian10048 Thanks! I don't think @wolfhall got a green light on this.

**Comment by brian10048** [comment]
@max3903 

> Set fsm.vehicle to inherit from fleet.vehicle based on the fleet_vehicle_id field 

This would be a delegation inheritance? If so, what should I do with the `name` field of FSM Vehicle, since it is already a field in Fleet vehicle?

**Comment by max3903** [comment]
@brian10048 Yes. Same as fsm.location and res.partner.

Set it to the same value of the fleet.vehicle one.
