### ISSUE TITLE
[12.0] fieldservice/maintenance/repair: after unlink all, field is_fsm_** is not correctly set 

### ISSUE THREAD

**Issue by zbik2607** [OCA/field-service#370]
When equipment  in FSM is unlinked, fields is_fsm_equipment should be set to False.

    @api.multi
    def unlink(self):
        equipments = self.mapped('maintenance_equipment_id') 
        res = super(FSMEquipment, self).unlink()
        for equipment in equipments:
            other = self.env['fsm.equipment'].search([('maintenance_equipment_id','=',equipment.id)])
            if not other:
                equipment.is_fsm_equipment = False  
        return res

Similar problem I see in fsm.location

**Comment by max3903** [comment]
@zbik2607 I believe this can be closed, right?

**Comment by zbik2607** [comment]
Similar fix is needed in fieldservice:  fsm.location and fsm.person  (fields: fsm_location,fsm_person)

    @api.multi
    def unlink(self):
        partners = self.mapped('partner_id') 
        res = super(FSMLocation, self).unlink()
        for partner in partners:
            locations = self.env['fsm.location'].search([('partner_id','=',partner.id)])
            if not locations:
                partner.fsm_location = False  
        return res

You close this issue and I create new or .... your decision!

**Comment by max3903** [comment]
...rename this one :)
