### ISSUE TITLE
[RFC] fieldservice_route

### ISSUE THREAD

**Issue by max3903** [OCA/field-service#380]
Depends: fieldservice
License: AGPL-3

A Field Service route is the sorted list of orders that one worker/vehicle will perform during a day.

This module allows you to manage your Field Service routes: when assigning an order to a worker and scheduling it, a route is automatically created for that worker and day.

# Configuration

* Go to Field Service > Configuration > Stages
* Define the workflow of your routes by creating new stages whose type is "Route"
* Go to Field Service > Configuration > Routes
* Create your routes by setting their name and selecting their territory

# Usage

* Go to Field Service
* Create or select an order
* Assign it to a worker and schedule it
* Go to Field Service > Dashboard > Day Routes. A new record has been created.

# Technical Specifications

## fsm.stage

- [x] Add a new stage_type "Route" (route)

## fsm.route.day

- [x] Add the object
- [x] Add a selection field "Name" with the 7 days of the week
- [x] Add the data with the 7 records

## fsm.route

- [x] Add a char field "Name" (name)
- [x] Add a many2one field "Territory" (territory_id) to fsm.territory
- [x] Add a many2one field "Person" (fsm_person_id) to fsm.person
- [x] Add a many2many field "Days" to fsm.route.day

## fsm.location

- [x] Add a many2one field "Route" (fsm_route_id) to fsm.route

## fsm.route.dayroute

- [x] Move the `fsm.route` object from the fieldservice module to this module and rename `fsm.route` current object to `fsm.route.dayroute`
- [x] Add a many2one field "Route" (route_id) to fsm.route
- [x] Add a many2one field "Team" (team_id) to fsm.team. Only shown if the user is in the FSM Team group.
- [x] Add a many2one field "Stage" (stage_id) to fsm.stage filtered with stage_type = route
- [x] Add a many2one field "Territory" (territory_id)
- [x] Add 2 float fields "Longitude" (longitude) and "Latitude" (latitude)
- [x] Add a many2one field "Last Location" (last_location_id) to fsm.location
- [x] Add a datetime field "Planned Start Time" (date_start_planned). The time of day when the worker starts to work, it needs to consider time zone and schedule for this worker (use default worker setting).
- [x] Add a many2one field "Start Location" (start_location_id) to fsm.location. The worker's day starts at this location. It can be a home, office, etc. (optional -use default worker setting)
- [x] Add a many2one field "End Location" (end_location_id) to fsm.location. The worker's day ends at this location. It can be a home, office, etc. (optional -use default worker setting)
- [x] Add a time field "Time before overtime (in hours)" (work_time). Time in hours, e.g. 7.5 hrs (configuration entry with default of 8 hrs for all workers)
- [x] Add a time field "Maximal Allowable Time (in hours)". E.g. 10 - maximal allowable time, includes overtime (configuration entry with default of 10 hrs for all workers)
- [x] Add a computed integer read-only field "Number of Orders" (order_count). Number of orders in the day route.

## fsm.order

- [x] Extend the create and write methods to:
* check if the person and date are set
  * Search for a day route to add the order to it
  * Otherwise create a new route
* Otherwise
  * if the order is the only one on the day route
    * Delete the day route
  * Otherwise remove the order for the day route

**Comment by hparfr** [comment]
Why the link between route and stage ?

A route can be just a linked list with all the orders the worker is assigned to, sorted by a key, like schedule_date_start.

Displaying subsets of route can be convenient, but it should not be enforced to day. I may need for some cases a couple of days or weeks.

**Comment by max3903** [comment]
@hparfr The day route will go through a workflow: To-Do, Confirmed, Done

**Comment by hparfr** [comment]
May be I don't understand the route concept.

In my understanding a route is a suite of FSM Orders. Because they are related one to one, you can estimate the time to travel from one location to another. And draw the locations on a map.

**Comment by max3903** [comment]
@hparfr The suite of FSM orders is a day route: it's the combination of the route and the day it is executed.

Example:
Route: North Sector, only scheduled on Tuesdays and Thursdays.
Day Route: List of FSM orders in the North Sector scheduled on Tuesday Nov 19th and assigned to John Doe with the truck 1.
