### ISSUE TITLE
[RFC] fieldservice_account_payment

### ISSUE THREAD

**Issue by max3903** [OCA/field-service#381]
Depends: fieldservice_account with #391
License: AGPL-3

This module allows the worker to accept payments during his work at the location.

# Usage

* Go to Field Service
* Select or create a Field Service order
* Click on the "Register Payment" button
* Select the Payment Method
* Enter the amount
* Validate

# Technical Specifications

## account.payment

- [x] Add a many2one field "FSM Order" (fsm_order_id) to fsm.order

## fsm.order

- [ ] ~~On the list of invoices (invoice_ids), add a button "Register Payment" to register the payment. Set the payment fields with:~~
* ~~fsm_order_id = id of the order~~
* ~~partner_id = using the customer on the invoice~~
* ~~partner_type = customer~~
* ~~payment_date = today~~
- [x] Add a smart button to display the list of payments related to the order
- [x] Add the required access rights for the worker to create payments

**Comment by murtuzasaleh** [comment]
#423
