### ISSUE TITLE
[RFC] Order, Location Sizes

### ISSUE THREAD

**Issue by brian10048** [OCA/field-service#384]
In my field service operation it is necessary to track the size of a field service order.  For example, the square foot area of a lawn.

The size of a field service order is typically based on the size of the location being serviced.

My company provides multiple sectors of services to one location which can be grouped using categories.  As a result, a location needs to have a size for each category.
  
Sizes need configurable units of measure.

A field service order template uses the size to calculate the expected duration for a field service order. (Example: each unit of size requires 'x' minutes to complete)

**Comment by hparfr** [comment]
Why not use the quantity on the sale order line ?

**Comment by brian10048** [comment]
I agree.  I would use the quantity of the sale order line for field services being sold.  The quantity of the sale order line would set the size of the field service order upon creating that order.

I was curious to know if anyone else has a need for this and any other comments on how to implement a size field on the field service orders and locations.
