### ISSUE TITLE
fieldservice_isp_flow: Schedule Date Start is always invisible

### ISSUE THREAD

**Issue by max3903** [OCA/field-service#389]
The Schedule Start Date field on the field service order is invisible in all stages (except Cancelled):

https://github.com/OCA/field-service/blob/a8608444fd42f8b37d60e512d32b92271ee4f7d5/fieldservice_isp_flow/views/fsm_order.xml#L63

I am not sure there is a good reason for this.

CC: @patrickrwilson

**Comment by patrickrwilson** [comment]
I agree, the eta really should always be shown.
