### ISSUE TITLE
[RFC] fieldservice_route_vehicle

### ISSUE THREAD

**Issue by max3903** [OCA/field-service#390]
Depends on fieldservice_vehicle and fieldservice_route

This module allows you to set the vehicle on the routes and day routes.

# Configuration

* Go to Field Service > Master Data > Routes
* Create or select a route
* Set the Vehicle

# Usage

* Go to Field Service > Operations > Day Routes
* Create or select a day route
* Set the vehicle

# Technical Specifications

## fsm.route

- [x] Add a many2one field "Vehicle" (fsm_vehicle_id) to fsm.vehicle

## fsm.route.dayroute

- [x] Add a many2one field "Vehicle" (fsm_vehicle_id) to fsm.vehicle
- [x] Add an onchange on the route field to set the vehicle of the route to the day route:
```
self.vehicle_id = self.route_id.vehicle_id.id
```

**Comment by brian10048** [comment]
LGTM

When can we implement [geospatial 223](https://github.com/OCA/geospatial/pull/223), add a lasso tool for selecting orders on the map, and create an action to optimize the driving using something like [this](https://developers.google.com/optimization/routing/vrp)?  :grin:

**Comment by max3903** [comment]
Aha, I will ask Santa if he is interested and has budget... ;-)

**Comment by brian10048** [comment]
@max3903 if you can ballpark an estimate please send me an email! 

:santa: might be more efficient if he had it!

**Comment by max3903** [comment]
@brian10048 I would need to investigate a bit to provide an estimate.

CC: @wolfhall

**Comment by wolfhall** [comment]
Brian.  This is also on my wishlist :)   
I worked some 18 years with VRP stuff and my team  designed our own algorithms.   I was hoping to plug this in before the end of the year but I don't have funding.

**Comment by damendieta** [comment]
Hi, I'd like to help with this issue, could you please tell me where can I download the base_geolocalize module, it's on the dependencies, but I only found it for v8.

Thanks a lot.

Daniel.

**Comment by bodedra** [comment]
@damendieta It's Odoo standard core module and you may find it under addons folder. Here is ref: https://github.com/odoo/odoo/tree/12.0/addons/base_geolocalize
