### ISSUE TITLE
[RFC] fieldservice_account

### ISSUE THREAD

**Issue by max3903** [OCA/field-service#391]
Some organizations allows their FSM persons to have access to the customer invoices.

# fsm.order

- [x] Add a one2many field "Invoices" (invoice_ids) to account.invoice using the field fsm_order_id
- [x] Show a smart button if there is more than one invoice related to the fsm order

**Comment by brian10048** [comment]
In #387 I did an `invoice_id` as you mentioned would be useful to add.  It could be changed to invoice_ids and accomplish the same thing.

Are there any security groups/settings to consider that will allow/restrict certain groups or even user specific access to the invoices?

**Comment by max3903** [comment]
@brian10048 In fieldservice_account, the FSM user needs to have read access to invoice.

In #381, they will accept payments so we will need to give them more permissions in `fieldservice_account_payment`.

**Comment by dreispt** [comment]
The design does not mention where to display the Invoices, I suggested adding it inside a new Notebook Page "Invoices".

**Comment by murtuzasaleh** [comment]
#430

**Comment by max3903** [comment]
@dreispt What about a smart button instead? `fieldservice_account_analytic` is adding an "Accounting" tab and that might be confusing to have Accounting and Invoices...

**Comment by brian10048** [comment]
I like the smart button too.  I would think many times only 1 invoice might be linked so a button would be easier than finding it in another tab

**Comment by dreispt** [comment]
The smart button will go again the requirement in #381 for the Order to have "Register Payment" buttons for the related Invoices. Should we then remove that requirement?

**Comment by max3903** [comment]
> The smart button will go again the requirement in #381 for the Order to have "Register Payment" buttons for the related Invoices. Should we then remove that requirement?

Done
