### ISSUE TITLE
[RFC] fieldservice_sale

### ISSUE THREAD

**Issue by max3903** [OCA/field-service#393]
This change will allow to create an FSM order for each sales order and link it to the delivery order and invoice.

# product.template

- [x] Add a selection field "Service Policy" (fsm_policy) with the options:
* "No service"
* "One service per sale order"
* "One service per sale order line"

# fsm.order

- [x] Add a many2one field "Sale Order" (sale_id) to sale.order

# sale.order

- [x] When the sale order is confirmed:
* For each line
  * if the product service policy is No service, do nothing (default Odoo behavior)
  * if the product service policy is One service per sale order, create a FSM order and set it on the sale order if it's not already done
  * if the product service policy is One service per sale order line, create a FSM order for each line
* set the fsm order on the pickings created by the sale order
- [x] When an invoice is created, set the fsm_order_id field to the related FSM Order of the line (or the order)
- [x] Add a smart button to show the FSM orders related to the sale order. Only when the sale order is confirmed (same behavior as picking).

| Products Service Policy | FSM Orders on Sale Order | FSM Order on Picking | FSM Order | FSM Order on Invoice |
|--------------------------------|----------------|-----------|-----------------|-------------|
| No service | False | False |  | False |
| One service per sale order | ID1 | ID1 | ID1 | ID1
| One service per sale order line | ID2 | ID2 | ID2 | ID2
| Multiple products with One service per sale order line | ID2 and ID3 | False | 2 FSM Orders with ID2 and ID3 | 2 invoices with ID2 and ID3
| Mixed products | ID1, ID2 and ID3 | ID1 | ID1, ID2 and ID3 | 3 invoices with ID1, ID2 and ID3

**Comment by brian10048** [comment]
@max3903 Can we figure out a way so that this isn't a company setting, but maybe a setting per each new sale order? I need to be able to do both methods of order creation in one company

**Comment by brian10048** [comment]
Is there a way this can be accomplished using routes on the products and choosing a route on each sale order line?

I will use my company specific examples for lack of better scenarios

I have some field service order templates as follows.  Each of these templates require different resources (ex: specialized vehicle and worker skills) to complete. 

| FS Order Template |
| ------------------ |
| Lawn Fertilization Order |
| Lawn Mowing Order |
| Sprinkler System Work Order |
| Landscape Enhancement Work Order |

These are some example products I sell on sale orders

| Product  | Type | related FS Order Template | Service Policy |
| ---------| ---- | --------------------| ---------------------- |
| Lawn Fertilizer Treatment | Service | Lawn Fertilization Order | sale order line |
| Lawn Mowing | Service | Lawn Mowing Order | sale order line | 
| Sprinkler Head | Stockable | Sprinkler System Work Order | sale order |
| Sprinkler System Controller | Stockable | Sprinkler System Work Order | sale order |
| Tree | Stockable | Landscape Enhancement Work Order | sale order |
| Mulch | Stockable | Landscape Enhancement Work Order | sale order |


A customer may need some trees planted, new mulch, and 4 new sprinkler heads installed.  We group this into one sale order for customer convenience to view only a single quotation.  Once confirmed, the ideal outcome would be that one FSM order of template Landscape Enhancement with the trees and mulch being grouped and another FSM order of template Sprinkler System Work Order with the sprinkler heads

**Comment by max3903** [comment]
@brian10048 This is an RFC so yes, the purpose of this is to find a solution that accommodate all our needs.

I like your solution and that would fit most cases I think.

**Comment by brian10048** [comment]
It can probably be done without the order template for more simple use cases.  I just included that to help illustrate my example.

I would be glad to work on this once we all agree on how to accomplish it, but I'm still struggling on the specifics.

**Comment by max3903** [comment]
I updated the description to include the table.

Regarding the template, we can have multiple templates generating one single order with:
* instructions = the concatenation of the content
* hours = the sum of the hours
* categories = the union of the categories

**Comment by brian10048** [comment]
If you edited the first comment, I don't think it posted

**Comment by max3903** [comment]
Aha. Good catch. I was still in the preview. Done.

**Comment by javimurcia** [comment]
A suggestion: Create a new invoicing policy "Invoice based on: FSM Order completion" so the sales order transitions automatically to the "to invoice" status when the FSM order is completed.

Also, FSM orders created from a sales order should have its accounting tab disabled, or have a warning, so a user doesn't mistakenly invoices the order twice (one from the sales order and another from the accounting tab).

Maybe the warning is the best option, so you can track the cost of the fsm order, and invoice the client if more work than quoted has been performed, or you needed more materials.

**Comment by brian10048** [comment]
@crazy-projects I have a PR #388 that will update the linked sale order line's `qty_delivered` field when a field service order is completed.  Field Service orders created from sales orders would then be invoiced from the sale order that created the field service order.

I agree that some improvements could be made to the Accounting section to help prevent duplicate invoicing in the case of a field service order being created from sales orders.  For me, any invoices for field service orders will almost always be based on a sale order (or a contract the sale order creates).  I need to use certain fields that the fieldservice_account module provides, but not necessarily the logic for invoicing based on employee timesheets or contractor bills.

@max3903, your thoughts?

Related to #391 as well

**Comment by max3903** [comment]
@crazy-projects @brian10048 Odoo already provides the configuration to invoice the quantity ordered or the quantity delivered. Let's use it. The changes here are related to how many FSM orders you expect when the sale order is confirmed.

**Comment by javimurcia** [comment]
> @crazy-projects @brian10048 Odoo already provides the configuration to invoice the quantity ordered or the quantity delivered. Let's use it. The changes here are related to how many FSM orders you expect when the sale order is confirmed.

Yep, better not reinvent the wheel, Brian's PR would work perfectly.

**Comment by brian10048** [comment]
@max3903 
Referring to the last 2 rows of your table in the spec: 
Do you think its necessary to create multiple invoices per sale order line here? I am having trouble determining how to do this.  

Let me know what you think about #403

**Comment by max3903** [comment]
@brian10048 #403 looks good :+1: 

I am not sure where you read multiple invoices per sale order line. If we have mixed products on the sale order and it is invoiced after delivery (when FSM order is complete), you can get:
* 1 invoice for the FSM order with all the products whose service policy is 'Per Sale Order'
* 1 invoice for the FSM order for each product whose service policy is 'Per Sale Order Line'

**Comment by brian10048** [comment]
Sorry, I meant multiple invoices per sale order.

The default Odoo behavior of a sale order puts all delivered lines onto one invoice correct?  I understand you want to split them based on service policy, but I am not sure how to accomplish this.

**Comment by max3903** [comment]
@brian10048 Correct. Everytime you run the wizard, it grabs all the invoiceable lines and put them on the same invoice.

I just checked action_invoice_create on sale.order. I would extend it to:
* call super()
* duplicate the invoice and move the invoice lines...

**Comment by brian10048** [comment]
Got it. Thank you

**Comment by brian10048** [comment]
@max3903 - #403 is checking all the boxes here in the spec.  Please give it a try!
