### ISSUE TITLE
Manage Vehicles

### ISSUE THREAD

**Issue by max3903** [OCA/field-service#4]
- [x] Add "Manage Vehicles" in the settings
- [x] Add Vehicles menu item in Master Data
- [x] Add Vehicle to the Route
- [x] Add Vehicles menu item in Reporting

**Comment by brian10048** [comment]
This will require adding a dependency to fleet in order to add fields to the fleet vehicle model.  ex: fsm_vehicle boolean that could be used to filter the Vehicles in the Master Data > Vehicles menu item view action 

Should the "Manage Vehicles" setting install a 'fieldservice_fleet' add-on that has the fleet dependency and accomplishes remaining/future items in the list?

**Comment by wolfhall** [comment]
We are treating FSM vehicles as a separate entity from fleet vehicles.  Initially we thought we could re-use the fleet vehicle tables but there is actually a different meaning between the two:

Fleet Vehicles in the standard module are assets that require maintenance and are tracked for mileage purposes.  Most dispatchers don't concern themselves with these aspects - they don't need classic fleet management functions.

Field Service Vehicles are a tool used in FSM that serves as an inventory location, has additional attributes (such as: has forklift, side load, ladder, etc.) and can be tied to a fleet service vehicle when needed.   keeping it separate allows us to be more flexible and not require the Fleet Management Module.  We are also dealing with many companies who use field service contractors who own their own vehicles.

**Comment by max3903** [comment]
Hello @brian10048,

The idea here is to start with a fsm.vehicle object.

If "Manage Vehicles" is selected in the settings, the "Install fleet module" (not sure about the label yet) option would appear. Checking this box would install the fieldservice_fleet module. In this module, the fsm.vehicle object would inherit the vehicle object provided by the fleet module. Like fsm.person inherits res.partner.
