### ISSUE TITLE
object with reference: owner_id - owner.id

### ISSUE THREAD

**Issue by jesulo** [OCA/field-service#40]
First of all, I thank you for sharing your module. Can I ask for an error that I have when converting a contact to fsm.location? Thanks for your time.

The operation can not be completed, probably due to the following:
- deletion: you may be trying to delete a record while other records still have references to it
- creation / update: a mandatory field has not been entered correctly

[object with reference: owner_id - owner.id]

**Comment by jesulo** [comment]
Thanks, I will do it.

**Comment by brian10048** [comment]
This should be resolved with cfb3fa9
