### ISSUE TITLE
New feature - Create Order instead Invoice

### ISSUE THREAD

**Issue by CarFla** [OCA/field-service#418]
Hi 
If we go to customer many time in a month we usually create unique invoice with all maintenance that we do.
With this addon there is no possible to group different field service.
Is possible to add the possibility to create a Saled Order from Field Service Order?
Thank you

**Comment by hparfr** [comment]
Hi,

With fieldservice_sale, you can create a sale order for your customer, confirm the sale, and add a new sale order line each time you do the maintenance.

You can have a similar behavior with fieldservice_contract if you use contracts instead of sale orders.

https://github.com/OCA/field-service/pull/403
https://github.com/OCA/field-service/pull/359

**Comment by CarFla** [comment]
> Hi,
> 
> With fieldservice_sale, you can create a sale order for your customer, confirm the sale, and add a new sale order line each time you do the maintenance.
 Ok, but in this manner I must modify a sales order every time that I do a Field Service job two time. 1 to create a new line, and create field service order, 
2 to indicate correct timesheet spent for field service job

I try to create a field service order from sales order, but when insert the timesheet in field service order The sale order not update with correct timesheet inserted.
I wrong something in configurating of FSM module?

I think that more other people not sell contract but go to their customer to repair something 2 or 3 time to terminate a job or because their customer call many time per month and after the end of job  want to make one invoice. For this kind of job it is more simple to create FSM order, and create sales order, and at the end merge all order to one invoice.

I'll study your suggestion anyway.

Thank you for your work.

**Comment by brian10048** [comment]
@CarFla I think you should try the `fieldservice_isp_account` module.
With it you can create your FSM order first.  Then, fill out your timesheets in the Accounting tab of FSM order form view. Confirm the accounting section and the order to generate an invoice based on timesheets of the order.

**Comment by CarFla** [comment]
@brian10048 Thank you for your reply, but... this is the same of create the invoice from one FSM order.
How we work: we have many customer without contract. They call us to repair machine. We go to customer, repair and note time spent to repair. If the same customer call for another machine to repair, we go to customer, make repair and note time.
At the end of month we merge all time note to make one invoice to customer.
FSM is good tool to trace all operation, and spare part used, but have only the option to make the invoice per FSM order. Yes, we can create a FSM order and mantain open until invoice time, but it is not correct to track service. And when we sell a product and make installation, we want to make one invoice for product and time, tracking time, and operation.
For example, if a plumber sells a boiler he will create a boiler order and make an intervention for installation. As it is now FSM the plumber must issue 2 invoices, one for the boiler, and one for installation.
Probably I mistake something I dont know.

**Comment by CarFla** [comment]
Another possible solution is to link project/task in timesheet registration in employee timesheets of FSM order. So Timesheet can invoiced from sales order that with service tracked from project/task.

**Comment by CarFla** [comment]
Hi
someone can create the feature?  Create a sales order from Field oder.

**Comment by babatoko** [comment]
Please keep the case open.
