### ISSUE TITLE
Error when track service and create FSM order from Sales Order line

### ISSUE THREAD

**Issue by CarFla** [OCA/field-service#442]
Hi
I try FMS sale on runbot.
I create a tracking for the service with Create one FSM order per sale order line and Timesheets on tasks
But when I create an Order with location inserted, look the error in file.

[error.txt](https://github.com/OCA/field-service/files/3988939/error.txt)

**Comment by brian10048** [comment]
I have a fix in the [PR here ](https://github.com/OCA/field-service/pull/424/files#diff-f5b45b9ece22e4bec23d64c6770aa2e4R73) which is in need of further review.

**Comment by brian10048** [comment]
@CarFla we merged #443 which includes a fix for this error
