### ISSUE TITLE
[RFC] fieldservice_activity

### ISSUE THREAD

**Issue by max3903** [OCA/field-service#450]
Depends on fieldservice
License: AGPL-3

On the Field Service order, the instructions allow you to enter the different tasks or activities that need to be performed as un-structured content.

This module allows you to define activity on a template/order, define whether the activity is required or not and a reference. Once an activity is completed, the date and person are stored.

All the required activities needs to be completed to complete the FSM order.

# Configuration

* Go to Field Service > Configuration > Settings
* Activate the FSM Order Templates if you don't want to keep creating the same activities

# Usage

## Templates

* Go to Field Service > Master Data > Templates
* Create or select a template
* Go to the Activities tab to add activities
* Set their name, whether they are required or not and a reference (i.e a URL)

## Orders

* Go to Field Service > Operations > All Orders
* Create or select an order
* Select a template to copy the activities from that template
* Create additional activities if necessary
* Complete them when they are done or cancel them
* Complete the order

# Technical Specifications

### res.config.settings

- [x] Add a boolean field "Manage Activities" (module_fieldservice_activity)

### fsm.activity

- [x] Add the object
- [x] Sort the records using the sequence field
- [x] Add a required char field "Name"
- [x] Add a boolean field "Required" (required). Default value is False.
- [x] Add an integer field "Sequence" (sequence). Use the "handle" widget when displaying the field in a list view.
- [x] Add a boolean field "Completed" (completed). Default value is False.
- [x] Add a datetime field "Completed on" (completed_on)
- [x] Add a char field "Completed on" (completed_by)
- [x] Add a char field (ref)
- [x] Add a many2one field "FSM Order" (fsm_order_id) to fsm.order.
- [x] Add a many2one field "FSM Template" (fsm_template_id) to fsm.template.
- [x] Set all fields as read-only if completed = True.
- [x] Add a method action_done to set:
* completed = True
* completed_on = now
* completed_by = self.env.user.name

## fsm.template

- [x] Add a one2many field "Activities" (activity_ids) to fsm.activity using fsm_template_id.

## fsm.order

- [x] Add a one2many field "Activities" (activity_ids) to fsm.activity using fsm_order_id.
- [x] Show the completed_on and completed_by fields if completed is true.
- [x] Extend _onchange_template_id to copy the activities from the template to the fsm order.
- [x] Extend the action_complete method to check that all the required activities are completed. Raise an error message otherwise: "You need to complete all the required activities to complete this order!"

# User Interface

## FSM Template

![Screenshot from 2019-12-24 15-30-30](https://user-images.githubusercontent.com/939952/71425858-869acb80-2667-11ea-86a0-78d38d714269.png)

## FSM Order with Activities

![Screenshot from 2019-12-24 15-32-03](https://user-images.githubusercontent.com/939952/71425865-91556080-2667-11ea-865b-35c8605b7e6b.png)

## FSM Order with Completed Activities

![Screenshot from 2019-12-24 15-44-34](https://user-images.githubusercontent.com/939952/71425869-9d412280-2667-11ea-9001-621c3a1f6ff4.png)

**Comment by brian10048** [comment]
@max3903 Looks like a good start to me and that you have a good bit of the work already done based on those screenshots!

What are your thoughts on adding a response type and response value field to activities? Similar to a quality control point in MRP app. For example, a pass/fail response, a numeric response within a range of values, a text response, or a pre-defined list of responses from which the user would choose at the time of activity completion.

**Comment by max3903** [comment]
Ping @wolfhall
