### ISSUE TITLE
fieldservice_stock: fsm_equipment.xml view domain error

### ISSUE THREAD

**Issue by barnarj** [OCA/field-service#468]
Hey Guys,

We have encountered an issue when attempting to add new fieldservice equipment and we wanted to bring it to your attention.

When creating a equipment entry in FSM (fsm.equipment), the _product_id_ field is used to filter for the _lot_id_ field.  The relation is: `product_id = product_id` (to stock.production.lot)

https://github.com/OCA/field-service/blob/e74f141114179842c9277cd61c6b775bedb6f005/fieldservice_stock/views/fsm_equipment.xml#L13-L15

**Problem**: when a _product_id_ is selected that has valid serial numbers and creates a field service equipment, there are no options available to select in _lot_id_.

![fsm_equipment_serial_bug](https://user-images.githubusercontent.com/37902375/72090404-ffdb2500-32db-11ea-8fd0-de487a7bb1c0.png)

![image](https://user-images.githubusercontent.com/37902375/72090431-0f5a6e00-32dc-11ea-9969-ae978696ec93.png)

![image](https://user-images.githubusercontent.com/37902375/72090456-18e3d600-32dc-11ea-8ce3-fac2f79139b9.png)

![image](https://user-images.githubusercontent.com/37902375/72090488-2bf6a600-32dc-11ea-80c4-5f70a6a3c30d.png)

Are we missing a critical implementation component in a setting somewhere, or is this a bug?

Thanks!
Jacob

**Comment by dreispt** [comment]
@max3903 Any idea about this?

**Comment by max3903** [comment]
@barnarj You get this behavior when creating an FSM equipment. Do you also get it during the modification?

CC: @osi-scampbell This looks like the same issue of the account when creating an invoice line... Can you help?

**Comment by osi-scampbell** [comment]
@max3903 Yes I can take a look

**Comment by barnarj** [comment]
@max3903 I'm sorry but I do not know if we are able to modify FSM equipment entries; we are not able to create a them and we currently do not have any FSM Equipment entries already available on any of our Odoo instances.

**Comment by dreispt** [comment]
@osi-scampbell Do you happen to have any work done on this?

**Comment by dreispt** [comment]
@barnarj Hello, both me and Steve were unable to reproduce it.
Below is an example I got from my test environment.

Can you double check please?
Are you sure that product has Serial# available in your database?

![image](https://user-images.githubusercontent.com/1246629/75995789-d7932f80-5ef4-11ea-9c96-9bb5a93cd860.png)

**Comment by dreispt** [comment]
We came to the conclusion this is not related t the FSM repo codebase.
Thank you!
