### ISSUE TITLE
Field Service Sale - Not creating FSM orders properly

### ISSUE THREAD

**Issue by brian10048** [OCA/field-service#475]
Sale Order Lines with products set to field_service_tracking = sale do not create FSM orders from a Sale Order confirmation when that sale order line is after a SOL with product set to field_service_tracking = line.

#### 2 FSM Orders created
![image](https://user-images.githubusercontent.com/25710115/72542852-cd3ca980-3852-11ea-96a1-21688fcbb279.png)

#### Only 1 FSM Order was created - should be 2
![image](https://user-images.githubusercontent.com/25710115/72543013-112fae80-3853-11ea-8a20-5e810ea4a878.png)

**Comment by brian10048** [comment]
@max3903 If I revert the changes you made in #469 at [these lines](https://github.com/OCA/field-service/pull/469/files#diff-f5b45b9ece22e4bec23d64c6770aa2e4R131-R142) it will fix this.

Any reason we need to keep your changes?  The method already handled a recordset of sale order lines before.

**Comment by max3903** [comment]
@brian10048 It is the same code within the loop on the records (we have the decorator api.multi).

**Comment by brian10048** [comment]
@max3903 Before you added the loop in #469 the code was looping towards the end of the method on two filtered recordsets.  Now with your added loop on the entire recordset the code `for so_line in rec.filtered( ...` doesn't make sense because rec is a single record and we wouldn't need to loop.  We don't need these nested loops, so I tried this way:
        
       for rec in self:
            if rec.product_id.field_service_tracking == 'sale':
                sale = rec.order_id
                so_fo_mapping = sale._field_find_fsm_order()
                rec.fsm_order_id = so_fo_mapping[rec.order_id.id].id
            if rec.product_id.field_service_tracking == 'line':
                rec._field_find_fsm_order()

This still did not create an FSM Order for the product with field_service_tracking = sale 

Which leads me to the _field_find_fsm_order method of Sale Order.  It doesn't create the FSM Order as intended for a SOL product with field_service_tracking = sale because there was already FSM Order(s) created by the SOL products with field_service_tracking = line

## Option 1
Reverting to my original code prior to #469 creates the FSM Orders for field_service_tracking = sale prior to creating any FSM Orders for the 'line' products

## Option 2
Find a way to modify the Sale Order _field_find_fsm_order method to create the FSM Order and ignore FSM Orders created by SOL 'line' products

**Comment by max3903** [comment]
@brian10048 Option 2

When FSM order is created for tracking = line, set the sale_id and sale_line_id fields

For product with tracking = sale, search for FSO with sale_id set and sale_line_id NOT set.
Create a new FSM order with sale_id set or update the found one
