### ISSUE TITLE
Cannot create invoice from sale order when products creating FSM order per line

### ISSUE THREAD

**Issue by carlgrosser** [OCA/field-service#485]
Odoo gets stuck loading when trying to invoice a sales order, and loses connection to server. Tested on runbot and got the same results.

- Product set as FSM order per sales order line creates this problem.
- Switching product to FSM order per sales order allows invoice to be created.

**Comment by brian10048** [comment]
Thanks @carlgrosser 

I'll take a look into this and see what needs fixed

**Comment by brian10048** [comment]
@carlgrosser I believe the issue has been fixed in #486
