### ISSUE TITLE
Repair order not created when saving FSM order

### ISSUE THREAD

**Issue by TumbaoJu** [OCA/field-service#487]
I tested the *fieldservice_repair* module on your runbot and on my own instance and in both cases, it didn't work.

I followed the configuration and usage instructions mentioned on the readme of the module and the repair order is not created when I save my FSM order(as it should be).

**Comment by brenoalef** [comment]
I'm having the same issue. Also, the repair field doesn't show up when I pick the related type.

**Comment by marcelsavegnago** [comment]
The method of creating the FSM order is commented. I asked a question in the PR that generated this change. I'm trying to understand what the restriction would be.

https://github.com/OCA/field-service/pull/241
