### ISSUE TITLE
[12.0] customer_id on fsm.location.person in fieldservice_account_analytic

### ISSUE THREAD

**Issue by osi-scampbell** [OCA/field-service#490]
In fieldservice_account_analytic, customer_id field is defined on fsm.locaiton.person however we don't add it to the form view. It is a required field that cannot be set from the from end and is not being set anywhere on the back end. I can see this field being very useful in the future but for now can I comment this field out?

To replicate:
Install fieldservice_account_analytic
Add a fsm.location.person to an fsm.location

**Comment by osi-scampbell** [comment]
@hparfr can you give me any insight into how we are using this field? Thanks!

**Comment by hparfr** [comment]
It has been deleted with this commit : 
https://github.com/OCA/field-service/commit/923042f1ab142c02d1b57c58d0b9cf7de282246f#diff-79dd1679ea9e4a9622da088af58ba85d

I didn't pay attention to this file during the review. 

@brian10048, do you know why it has been removed?

**Comment by brian10048** [comment]
Originally it looks like customer_id field for fsm.location.person was moved from [here](https://github.com/OCA/field-service/commit/280039a676f259024fb6eba5b3863dc4ccca65af#diff-6b58de5ed729e9dab0fd7d20b0e55ac6L21-L22) to be replaced [here](https://github.com/OCA/field-service/commit/3a9deaf30e8e8b0d7693a45fd41d0c4b1d15953d#diff-b04a09ddc359b102f7a4c4a316d23958R10-R13), but it was not set as a related field like before the change.

I don't think I intended to remove the customer_id field from the fsm.location.person view in https://github.com/OCA/field-service/commit/923042f1ab142c02d1b57c58d0b9cf7de282246f#diff-79dd1679ea9e4a9622da088af58ba85d 

Regardless, I'm not really sure how the customer_id field would be used on the fsm.location.person  Either adding it back to the view back and reset the field as related or removing the field entirely is OK with me

**Comment by hparfr** [comment]
Yes it has been moved  from fieldservice to fieldservice_account then fieldservice_account_analytic.

I don't use this field, because for all my use cases, the customer_id (= billing_id) is coming from a sale_order or a contract.contract.
See #331

**Comment by brian10048** [comment]
Closed with #494
