### ISSUE TITLE
Manage Teams

### ISSUE THREAD

**Issue by max3903** [OCA/field-service#5]
- [x] Add "Manage Teams" in the settings
- [x] Add Teams menu item in Configuration and only show it to the Manage Teams group. Each Team has a specific ordered list of Stages
- [x] Add Team on the Field Service Person and only show the field to the Manage Teams group
- [x] Add Team on the Order and only show the field/filter to the Manage Teams group
- [x] Change the Dashboard to show statistics and shortcuts by Team (# of Unassigned Orders, # of Unscheduled Orders, button to open the Kanban view of Orders)

**Comment by dreispt** [comment]
@max3903 I suggest that the base module includes basic Team support (the Team Model), so that the Stages can be defined by Team.
In my view, teams are for Orders what Projects are for Tasks.
I can work on this.

**Comment by max3903** [comment]
@dreispt Thanks
