### ISSUE TITLE
Change to custom_color fields when Google color picker is installed

### ISSUE THREAD

**Issue by wolfhall** [OCA/field-service#504]
When field-service/fieldservice_google_marker_icon_picker is installed it modifies the custom_color behavior and breaks the color fsm.stage logic that is used to color service order in the timeline view and elsewhere.

Improvements:
1) for fsm.stage custom_color, implement a check to make sure users enter a valid Hex Code.
2) When field-service/fieldservice_google_marker_icon_picker is installed:  Make the custom_color field invisible on the fsm.stage form and display the color picker field.  The user can use the color picker it to chose a color icon.  When the user picks a color, we will automatically populate the hidden custom-color Hex code field since this is what is driving the stage colors elsewhere.

**Comment by murtuzasaleh** [comment]
#502 
#503
