### ISSUE TITLE
[RFC] fieldservice_portal (+ Mobile App)

### ISSUE THREAD

**Issue by max3903** [OCA/field-service#541]
Dependencies: fieldservice, portal
License: AGPL

This module provides external workers access to their FSM orders through the portal or the mobile app.

# Technical Specifications

## fsm.stage

- [ ] Add a boolean field "Show on the portal" (show_portal)

**Comment by brian10048** [comment]
Any thoughts about customer access to view the orders assigned to their locations?

**Comment by max3903** [comment]
@brian10048 Sure, but we need to figure out #524 first... :)

**Comment by brian10048** [comment]
I knew that was coming!  I'll check back on that issue and add some of my thoughts in the near future to maybe help push it along
