### ISSUE TITLE
Request workers flow

### ISSUE THREAD

**Issue by ska-ibees** [OCA/field-service#562]
Hello,
I am trying to understand the purpose of "Request workers" in FSM order. 
I assumed it is like sending a request to multiple workers with notifications so that anyone on the list can accept and assign that FSM order to him/her self.
In fact, I have a use case, where multiple workers (subcontractors ) are linked with a location. We need to send a request to all workers (Based on skills and location and filter in the "Request Workers" serve the purpose) where they get notified about that request to accept or reject it.

But while testing and also looking into the code, I do not see such workflow. 

Could anyone please help to understand the purpose of "Request workers".

Thanks

**Comment by brian10048** [comment]
@go4site The idea behind Request Workers is similar to your use case.  However some of these functionalities are not yet implemented.  See #166 

cc: @max3903

**Comment by ska-ibees** [comment]
Thanks @brian10048. 
@max3903 is there any progress in this regard?

**Comment by max3903** [comment]
@patrickrwilson can provide more insight but the process is as follows:

* An email is sent to the request workers with the fsm order details.
* They reply by providing their ETA at the location
* Based on the ETA and other factors, the dispatcher decides on which worker to assign the order to.
* When the order is assigned, the winning worker and the other workers gets an email with their result.

**Comment by brian10048** [comment]
@max3903 @patrickrwilson  - Are you guys using the fieldservice_stage_server_action module to facilitate the added functionality of emailing the workers?

**Comment by patrickrwilson** [comment]
@brian10048 Yes, we use those. Here is a common scenario we have....

We have regions where we use several sub contractors listed for locations. In our scenario, the sub contractors accept and schedule the FSO with the location/customer.
- We create the FSO. We do send an email to the location/customer at this point to notify them a FSO has been created. 
- Several sub contractors that are assigned to that location are added to the request worker area. FSO moves to requested stage and an email goes to them stating a FSO is available.
- The first sub contractor who replies that they accept the FSO usually gets it assigned to them. FSO moved to assigned stage and an email goes to them stating that the FSO has been assigned to them but an ETA is needed. An email goes to the other requested contractors stating the FSO has been assigned to someone else.
- The assigned contractor provides an ETA once they have scheduled with the location/customer. The FSO is moved to scheduled and an email goes to both the assigned worker and the location/customer with the scheduled ETA.
- Contractor works the FSO, provides closing info and labor/travel and when the FSO is closed, an email goes to the contractor and location/customer stating the FSO has been closed.

**Comment by brian10048** [comment]
Great information.  Thank you for sharing

**Comment by ska-ibees** [comment]
Workflow is much clear now. 
Thanks all for sharing the great insights.

**Comment by ska-ibees** [comment]
Hi again!

@patrickrwilson 
Could you please confirm that how workers are accessing their requested/assigned workorders?
Is it just through emails or do they have access to orders itself via backend or portal? For example, in your mentioned workflow, how does assigned contractor provide ETA? 
I was looking for some interactive interface where records coule be seen and handled by portal users (Workers, location POCs or Owners etc.). 

I am working on a module for this purpose, it is still WIP but you can see an order could be accessed by portal user and get signed and confirmed. Please see [ demo here](http://ibees.biz/dn/FSM_Portal.webm)

**Comment by patrickrwilson** [comment]
> Hi again!
> 
> @patrickrwilson 
> Could you please confirm that how workers are accessing their requested/assigned workorders?
> Is it just through emails or do they have access to orders itself via backend or portal? For example, in your mentioned workflow, how does assigned contractor provide ETA? 
> I was looking for some interactive interface where records coule be seen and handled by portal users (Workers, location POCs or Owners etc.). 
> 
> I am working on a module for this purpose, it is still WIP but you can see an order could be accessed by portal user and get signed and confirmed. Please see [ demo here](http://ibees.biz/dn/FSM_Portal.webm)
> 
> 

So for us, we have both sub contractors and employees. The employees can schedule and edit FSO's directly because they have Odoo user accounts however our sub contractors are just communicating with our dispatch team directly via phone or email to confirm and schedule FSO's. So, having the ability to let our sub contractors access FSO's via the portal would be great. Please include me on your module PR so I can help review.

**Comment by ska-ibees** [comment]
Alright!
I am adding some more features to streamline Portal access for workers and customers. So far, I have created a separate model to manage requests/responses to keep actual order isolated during the negotiation and worker evaluation, etc. Idea is to provide portal access at every stage of the process.
Let me complete a prototype for a specific use case. Afterward, it will create a more generic version to be shared in a PR. I would definitely need your help to review it.

**Comment by dhecar** [comment]
Hello, I am trying to understand how the worker uses the module. I have a couple of questions.

My workers are assigned as a user in the fsm module, but they cannot see the buttons to change the phase of the order (started, en route) although they can drag the kanban. In addition they cannot complete the order because dragging cannot. Is this normal?

And a second question. 2 days a week or 1 day a week, my workers take material from my warehouse. I make an internal transfer to the vehicle for traceability. They go to the customer's house to do an installation (router). The router is not pre-assigned in FSM order because they can install any router they have in the vehicle. How can I indicate which router I have installed and decrease the stock of the vehicle store?
