### ISSUE TITLE
Question: set location equal to customer

### ISSUE THREAD

**Issue by CarFla** [OCA/field-service#571]
I testing Field Service.
For me is natural that location is the customer's address.
But when install Field Service locations list is empty.

I go to Contacts->Field service Tab, and I see Is a FS Location with check option. But If i try to modify that check not active it is not possible.
I try in Runbot also and either no check possible.

I search in configuration to active this option but i dont find nothing.

If i create a new locations for Field Service that will be a duplication of customer data, so i think it is not correct.

What I doing wrong? Thank you.

**Comment by brian10048** [comment]
Hi @CarFla 

You can convert existing contacts to a Field Service Location using the Action menu on a contact record and select Convert to FSM Record.  (Or from a list view, select multiple contacts to convert multiple records.)
![image](https://user-images.githubusercontent.com/25710115/82231516-4a5c5600-98fb-11ea-998a-d14fce86d668.png)


Then chose Location on the wizard 
![image](https://user-images.githubusercontent.com/25710115/82231558-55af8180-98fb-11ea-969c-4c2de90c0acf.png)

**Comment by CarFla** [comment]
what a stupid I am :( :( 

Thank you
