### ISSUE TITLE
[IMP] Add check for existing fsm.equipment before creating during stock move

### ISSUE THREAD

**Issue by barnarj** [OCA/field-service#579]
Hello,

We have encountered an issue with the _action_done() extension in fieldservice_stock/models/stock_move.py - we are an ISP and regularly deploy/recover/re-deploy equipment to different customer locations over time.

Currently the implementation attempts to create an fsm.equipment record without first checking to see if one already exists:

https://github.com/OCA/field-service/blob/3cfdc3676dccfcc2a2f3dd0e07066c5524c46830/fieldservice_stock/models/stock_move.py#L22-L32

I would like to propose altering this method to first check if an existing equipment_id already exists before automatically creating a new one, and if one does exist to update the line.lot_id.fsm_equipment_id to it instead.

```
    def _action_done(self):
        res = super()._action_done()
        for rec in self:
            if rec.picking_code == 'outgoing' and rec.state == 'done':
                if rec.product_tmpl_id.create_fsm_equipment:
                    for line in rec.move_line_ids:
                        vals = self.prepare_equipment_values(line)
                        equipment_id = self.env['fsm.equipment'].search(
                            [('name', '=', line.lot_id.name)]
                        )
                        if equipment_id:
                            line.lot_id.fsm_equipment_id = equipment_id.id
                        else:
                            line.lot_id.fsm_equipment_id = \
                                rec.env['fsm.equipment'].create(vals)
        return res
```

Thanks!
Jacob

**Comment by barnarj** [comment]
@osi-scampbell  Any chance you could help me get a little traction on this simple fix?

**Comment by dreispt** [comment]
Hi @barnarj We would need a Pull request to be able to merge the change. Can you propose one please?

**Comment by barnarj** [comment]
https://github.com/OCA/field-service/pull/644
