### ISSUE TITLE
QUESTION: Why I have to fill date_start date_end manually?

### ISSUE THREAD

**Issue by dhecar** [OCA/field-service#587]
Why not this two fields are filled when i change the status of the order, from scheduled  to route, and from started to completed?

**Comment by brian10048** [comment]
The status (stage) of the order can be configured to have as many or as few stages as required for your particular use case.  If you would like to update the start date or end date of the order when it reaches a particular stage/status, you can use the module fieldservice_stage_server_action.

With this module you will be able to define your own server action that is executed when an order enters a specific stage.

This allows a higher level of flexibility and customization for everyone's individual use cases.

**Comment by dhecar** [comment]
Ok, i'll try, thanks
