### ISSUE TITLE
QUESTION: User permissions

### ISSUE THREAD

**Issue by dhecar** [OCA/field-service#588]
HI, I don't understand why a worker, that have an odoo user and permissions of user in the module FSM can't complete the order.

That user can move the kanban order from scheduled to started, in route, all the time they want ( this is another question, why?), but can't complete the order... it's the normal behaviour??

**Comment by brian10048** [comment]
@dhecar Are you trying to move the order to complete stage from the kanban view? This behavior is not allowed.

You will need to use the button in the form view to move the order to complete stage. This ensures that the `action_complete` function is called

**Comment by dhecar** [comment]
If i assign to my worker in the permissions page of the user, the user permission, i can't put the order to complete, only exist the edit button, but i can move to other stages moving the kanban card.

**Comment by brian10048** [comment]
@dhecar I submitted a pull request (#606) to modify this behavior. I agree that a user permission level should have the complete button available.  It can be merged once we receive a consensus on this change
