### ISSUE TITLE
[RFC] Add Customer field to FSM order list?

### ISSUE THREAD

**Issue by dreispt** [OCA/field-service#632]
I noticed we don't have a Customer field available in the FSM Orders list.
There is a Contact field, but this is not the same thing.
The local Contact might not be directly related to the Customer ordering the service. 

Is this field really missing?
CC @max3903 @wolfhall @brian10048 

Thanks!

![image](https://user-images.githubusercontent.com/1246629/92607820-8ea9a280-f2ac-11ea-977a-1ee309cba9e4.png)

**Comment by dreispt** [comment]
I see there is a `customer_id` field.
I'm considering proposing a change to the list view, to have it visible there,.
Agree?

**Comment by hparfr** [comment]
[REDACTED] I was answering looking at the wrong file

customer_id is in field_service_account_analytic. I'm ok to add it in the fsm order tree view in field_service_account_analytic module
