### ISSUE TITLE
Cannot create a Maintenance Request for FS Equipment from Field Service.

### ISSUE THREAD

**Issue by felixsniper** [OCA/field-service#635]
Hi OCA,

I am using Odoo V12 Community.

I cannot create a Maintenance Request for FS Equipment from Field Service App. Please help give me an advice if I am wrong  in some step.

**Step to Reproduce:**
1) Create an FS Equipment "White Desk" from Field Service App, assign it to specific Maintenance Team.
2) Go to Field Service -> Create a new FS Order
3) Choose FS Type as Maintenance
4) In Equipments Tab -> Add FS Equipment "White Desk"
5) Save the FS Order  =>  No Request is created in Odoo Maintenance

Workaround:
I added the Stage for Equipments in Field Service module. (For example: "New Request" ->  "Confirmed" -> "Done".)
In "Confirmed" Stage, I choose Server Action as "Create Maintenance Request". 
![image](https://user-images.githubusercontent.com/69030714/92718413-fb479e80-f38b-11ea-9cdb-480bfa62ac16.png)

I tried to reproduce as the above steps (Step to Reproduce)
Then I changed the stage of the FS Equipment "White Desk" from "New Request" to "Confirmed". But no Request is created in Odoo Maintenance.

Please help check if I was wrong in some step, and give me an advice.

Thanks & Regards.
Felix.

**Comment by marcelsavegnago** [comment]
I sent a PR to correct the maintenance order generation. It is missing that it is approved and merged.
https://github.com/OCA/field-service/pull/580

**Comment by felixsniper** [comment]
Hi @marcelsavegnago,

From #634.
Thank you for you feedback,

**Testing Enviroment:**
+ Odoo CE V12 (From Odoo Official)
+ Field Service - v.12.0.2.12.1
+ Field Service - Stage Server Action v.12.0.2.0.0
+ Field Service - Maintenance v.12.0.1.1.0
=> This issue still happened

I downloaded all Field Service Apps/Add-ons from Odoo App Store.
Is there anything else that I need to check?

Thanks & Regards,
Felix

**Comment by felixsniper** [comment]
Hi @marcelsavegnago,

It worked after merging the PR #580 to current Field Service Git Repository.
Please help me to close this ticket.

Have a nice working day,
Thanks & Regards,
Felix Nguyen.

**Comment by marcelsavegnago** [comment]
Hi @felixnguyen-epiklah,

You can help by reviewing the PR.

**Comment by felixsniper** [comment]
Hi @marcelsavegnago 

I reviewed the PR #580 

Thank you for your help,
Regards,
Felix Nguyen.
