### ISSUE TITLE
Field Service Maintenance 11.0.0.0.1

### ISSUE THREAD

**Issue by max3903** [OCA/field-service#66]
Depends on fieldservice_stock and maintenance
License: AGPL-3

# Module Description
Odoo Maintenance App does not support Field Service operations for equipments outside the company facilities. On the other hand, the Field Service App does not support a maintenance schedule generating preventive maintenance request.

This module allows you to merge equipments from Field Service and Maintenance and have a maintenance schedule for FSM equipments as well as Field Service capabilities for maintenance equipments.

# Configuration
* Go to Field Service > Master Data >  Equipments or Maintenance > Equipments
* Create or select an equipment
* Specify the maintenance schedule

# Usage
* Maintenance requests related to a FSM equipment will create a FSM order
* Go to Field Service
* Create or select a FSM order and select the type Maintenance.
* Select the maintenance team, the equipment and the location
* Upon saving, a maintenance request will be created with the information from the FSM order.

# Technical Specifications

## maintenance.equipment
- [x] Add a boolean field "Is a FSM Equipment" (is_fsm_equipment)

## maintenance.request
- [x] If the selected equipment is a FSM equipment, create a FSM order (of type Maintenance) and link it to the request

## fsm.equipment
- [x] Add a many2one field "Maintenance Equipment" (maintenance_equipment_id)
- [x] Inherit from maintenance.equipment using maintenance_equipment_id

## fsm.order
- [x] Add the option "Maintenance" to the type list
- [x] Add a readonly many2one field "Maintenance Request" (request_id) to maintenance.request.  The field is displayed only if the type is "Maintenance".
- [x] Add a many2one field "Maintenance Team" (maintenance_team_id) to maintenance.team. The field is displayed only if the type is "Maintenance".
- [x] When a fsm.order with the "Maintenance" type is created, a maintenance request is created with:
    * Name = name of the fsm.order
    * Created by = current user
    * Equipment = maintenance equipment of the related FSM Equipment
    * Category = Category of the related maintenance equipment
    * Request date = Today
    * Maintenance type = Corrective
    * Maintenance Team = Team of the related fsm.order
    * Scheduled Date = Requested date of the fsm.order
    * Description = Notes of the fsm.order

**Comment by dreispt** [comment]
Looks like a good compromise 👍
