### ISSUE TITLE
[13.0] fieldservice: Gantt Chart

### ISSUE THREAD

**Issue by osi-scampbell** [OCA/field-service#667]
Hello,

I can see we have migrated the fieldservice module to v13, however it appears we did not migrate the gantt chart (timeline view), do we know why this is?

Gantt Chart in v12
![image](https://user-images.githubusercontent.com/39602586/98397920-5bba2b80-201d-11eb-822e-93bed34d296c.png)

No Gant Chart in v13
![image](https://user-images.githubusercontent.com/39602586/98397994-72f91900-201d-11eb-8fbc-82d523856e59.png)

**Comment by brian10048** [comment]
@osi-scampbell Check out #521 - When base fieldservice was being migrated to 13 the dependency for the gantt chart was not migrated yet itself https://github.com/OCA/field-service/pull/513#issuecomment-597020470

**Comment by osi-scampbell** [comment]
@brian10048 Thanks for the quick response, so we have split it into a separate module. I think that is smart, but it looks like it has been held up. I will reach out to the developer and see if we can get that back on track
