### ISSUE TITLE
`fieldservice`module abusive dependencies?

### ISSUE THREAD

**Issue by dreispt** [OCA/field-service#674]
I note that the `fieldservice` has dependencies on modules that don't seem necessary for it to work.
For example, `partner_fax` and `web_timeline`.
In my opinion if they not essential, the installation of those modules should be optional, and not be in the dependencies.
Such a change is simple wouldn't have an impact on existing installations.

**Comment by pedrobaeza** [comment]
Yeah, I agree and don't see the connection.

**Comment by bodedra** [comment]
timeline view functionality provided by web_timeline module and v12 fieldservice module has used timeline functionality.

In v13 fieldservice module has dropped that functionality. I will share discussion link for reason.

**Comment by brian10048** [comment]
`web_timeline` has already been separated as of v13
Agreed that `partner_fax` isn't very essential either

While we are on the subject of dependencies...
I feel that the `fieldservice_stock` module has extra dependencies on some OCA `stock_request` modules.  For me it would be better to split into one module that depends on base stock module and another one for the stock_request modules.  I'll do the work to split up `fieldservice_stock` if others are OK with that change

**Comment by pedrobaeza** [comment]
Yes, please!

**Comment by bodedra** [comment]
I take my words back for dropped functionality. It actually timeline functionality separated in new module called fieldservice_timeline. Here is open PR https://github.com/OCA/field-service/pull/521

**Comment by bodedra** [comment]
@dreispt For fieldservice v13, we can remove dependency of `partner_fax` and `web_timeline` modules.

**Comment by hparfr** [comment]
`base_territory` can be removed too I guess.
