### ISSUE TITLE
settings can be clicked but after reload they are not active in Odoo 14 for Field Service

### ISSUE THREAD

**Issue by Stephanisk** [OCA/field-service#746]
Hi,

Looking for a solution. When i go Field Service => Configuration => Settings:

I can select certain settings and save that will remain active, but the majority, when they are clicked they dissappear after saving again. For instance Manage Recurring Orders, Manage Tags, FSM Location Builder, Manage Distribution, .....

Is there any solution to activate these things, or are the modules not available yet for Odoo 14

**Comment by brian10048** [comment]
Hello @Stephanisk 
These modules are not yet migrated to v14
Once migrated, these settings will be functional
