### ISSUE TITLE
[12.0]Required a partner id field in a FSM Location.

### ISSUE THREAD

**Issue by AmmarOfficewalaSerpentCS** [OCA/field-service#755]
Hi OCA,

Step to reproduce:-
1:- Field service -> Master data -> Location
2:- Click on a crate 
3:- Enter a value in the required fields.
4:- Click on a save.

Result :- 
![Project12](https://user-images.githubusercontent.com/36848414/113814989-1f3b5900-9790-11eb-8553-969d0653a278.png)

Expected Result:-

It needs to save without getting any warning.

**Comment by HekkiMelody** [comment]
This is the same issue as #683, and it's repeated in multiple places in the code, not just locations.
