### ISSUE TITLE
Fieldservice_equipment_stock error on stock move action confirm

### ISSUE THREAD

**Issue by castalie-dev** [OCA/field-service#829]
1. Install module Fieldservice_equipment_stock
2. Validate a stock.picking IN movement and you will get that error
[Video record link](https://recordit.co/MT8SGFNEKq)
3. You will get this error message:

```
  File "/opt/odoo/addons/stock/models/stock_picking.py", line 942, in button_validate
    pickings_not_to_backorder.with_context(cancel_backorder=True)._action_done()
  File "/opt/odoo/addons/sale_stock/models/stock.py", line 78, in _action_done
    res = super()._action_done()
  File "/opt/odoo/addons/stock/models/stock_picking.py", line 763, in _action_done
    todo_moves._action_done(cancel_backorder=self.env.context.get('cancel_backorder'))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: _action_done() got an unexpected keyword argument 'cancel_backorder'
```

Thanks in advance for your help

**Comment by smangukiya** [comment]
@castalie-dev : Thanks for catching this up. Here is the PR which should resolve this issue. https://github.com/OCA/field-service/pull/830. Will merge it once all checks are clear.

**Comment by castalie-dev** [comment]
@smangukiya Thanks for your help. It did resolve this issue but another one appears. I created another issue.

**Comment by smangukiya** [comment]
> @smangukiya Thanks for your help. It did resolve this issue but another one appears. I created another issue.

@castalie-dev : Will review this one soon, Thanks
