### ISSUE TITLE
Adding translations in transiflex, how do i get permissions to do that?

### ISSUE THREAD

**Issue by MrTango** [OCA/field-service#855]
BTW the transiflex graph is missing in the 14.0 branch, or is deprecated to use it?
https://translation.odoo-community.org/projects/field-service-14-0/

**Comment by smangukiya** [comment]
> BTW the transiflex graph is missing in the 14.0 branch, or is deprecated to use it? https://translation.odoo-community.org/projects/field-service-14-0/

@MrTango : You are right, somehow it missed in recent migration. you are more than welcome to add it back to 14.0 branch.

Thank you

**Comment by brian10048** [comment]
@MrTango you can register to add translations here: https://translation.odoo-community.org/accounts/register/
