### ISSUE TITLE
[14.0][FIX] - Activating recurring orders not taken in place

### ISSUE THREAD

**Issue by marcos-mendez** [OCA/field-service#862]
When activating the recurring orders on field-service config it is not activated in the system neither in RunBot or Local LXC development.

## Module
field-service

![output](https://user-images.githubusercontent.com/38361760/145272288-4eb1b08e-bd93-490d-bc90-2b4365e13248.gif)

**Comment by marcos-mendez** [comment]
https://github.com/OCA/field-service/pull/859

Maybe can solve the problem, didn't tested

**Comment by brian10048** [comment]
@marcos-mendez once merged #859 will solve the issue

**Comment by marcos-mendez** [comment]
> @marcos-mendez once merged #859 will solve the issue

Thanks for the support
