### ISSUE TITLE
Migration of fieldservice_stock_request to Odoo 14 

### ISSUE THREAD

**Issue by aymenrahmay** [OCA/field-service#888]
We are using the field management service and we need to allow the technician to consume some products from his warehouse 
so we want to know :
If the module fieldservice_stock_request will be migrated to the 14 version?
Or is there any already migrated future  can allow us to do this ?

**Comment by brian10048** [comment]
The migration status of field service modules to v14 is tracked here #646
There is a pull request for the fieldservice_stock_request module here #813
