### ISSUE TITLE
[14.0] fieldservice: How are orders moved between stages

### ISSUE THREAD

**Issue by TheCloneMaster** [OCA/field-service#892]
Hi,
At least in V14, I can not find how to move an order between stages, besides the "complete" and "cancel" buttons or moving the order between stages in Kanban mode.  Are these the only intended ways of doing this?

If customer has many stages, it would be better to click on the correct stage in the "statusbar" instead of having to switch to Kanban
Regards,
-Mario

**Comment by HarryLinden** [comment]
Hello,
I use V12, Mario's suggestion is a good one. I brought this up with my IT team as well. Currently use this function in Helpdesk all the time.
