### ISSUE TITLE
Printing report on fsm.order error when using French

### ISSUE THREAD

**Issue by jbjour** [OCA/field-service#893]
French translation even translates technical fields
in [fr.po](https://github.com/OCA/field-service/blob/5edfe3f4dc3399b1f9901188679835c3fbe3ae78/fieldservice/i18n/fr.po#L59) and [fr_FR.po](https://github.com/OCA/field-service/blob/5edfe3f4dc3399b1f9901188679835c3fbe3ae78/fieldservice/i18n/fr_FR.po#L59)

```
#. module: fieldservice
#: model:ir.actions.report,print_report_name:fieldservice.action_report_fsm_order
msgid "'Service Order - %s' % (object.name)"
msgstr "'Commande de service - %s' % (objet.nom)"
```

## Module
fieldservice

## Describe the bug
When using the print (imprimer) button on fsm.order an error is raised

## To Reproduce
V14 install french language and print an fsm.order on it's form view

1. Install french on DB
2. Go on any fsm.order
3. Print it

**Expected behavior**
Printing the actual report

**Comment by pleirb** [comment]
> French translation even translates technical fields in [fr.po](https://github.com/OCA/field-service/blob/5edfe3f4dc3399b1f9901188679835c3fbe3ae78/fieldservice/i18n/fr.po#L59) and [fr_FR.po](https://github.com/OCA/field-service/blob/5edfe3f4dc3399b1f9901188679835c3fbe3ae78/fieldservice/i18n/fr_FR.po#L59)
> 
> ```
> #. module: fieldservice
> #: model:ir.actions.report,print_report_name:fieldservice.action_report_fsm_order
> msgid "'Service Order - %s' % (object.name)"
> msgstr "'Commande de service - %s' % (objet.nom)"
> ```
> 
> ## Module
> 
> fieldservice
> ## Describe the bug
> 
> When using the print (imprimer) button on fsm.order an error is raised
> ## To Reproduce
> 
> V14 install french language and print an fsm.order on it's form view
> 
> Steps to reproduce the behavior:
> 
>     1. Install french on DB
> 
>     2. Go on any fsm.order
> 
>     3. Print it
> 
> 
> **Expected behavior** Printing the actual report
![imagen](https://github.com/user-attachments/assets/ec9fd22f-ce41-4760-8e9d-39fa9167118a)
In v16 the same thing happens for es.po, a quote is missing **'**
```
msgid "'Service Order - %s' % (object.name)"
msgstr "Orden de servicio - %s' % (object.name)"
```
