### ISSUE TITLE
Manage Skills: fieldservice_skill

### ISSUE THREAD

**Issue by max3903** [OCA/field-service#9]
# Module description

Odoo Field Service App allows to assign any FS person to any FS order. For some organizations, they cannot assign any FS person to any order. They needs to manage the skills of the FS persons and reduce the list of potential FS persons on an order to avoid wrong assignment and mis-configuration. The skills of the selectable FS persons on a service order needs to match the required skills to perform the order.

This modules allows you to set skills on categories to automatically set those skills on the order. It also allows you to set the skills to the field service person with their level. On the order, the list of field service persons is filtered with the skills and the location so you can only assign the right person to the order.

# Configuration
* Create or edit your categories to set skills
* Create or edit your persons to set their skills and skill levels
* Create or edit your territories to set their field service persons
* Create or edit your locations to set their territories

# Usage
* Create an order, set the template and the location. 
  * The categories and skills are set based on the template.
  * The field service person is set to the preferred person if skills matches.
  * The list of field service persons is filtered with the one serving the location (using the territory) and having the skills

# Dependencies
- [x] #37 
- [x] hr_skill 11.0.2.0.0: https://github.com/OCA/hr/issues/503

# Configuration
## Settings
- [x] Add the "Manage Skills" option in the setting panel to install the fieldservice_skill module
## Categories
- [x] Add a many2many field "Skills" (skill_ids) to hr.skill on fsm.person.category
## Skills
- [x] Add a Skills menu item
- [x] Add a fsm.person.skill object
- [x] Add a required many2one field "Field Service Person" (fsm_person_id) to fsm.person
- [x] Add a required many2one field "Skill" (skill_id) to hr.skill
- [x] Add a required selection field "Skill Level" (skill_level_id) with: 0 Junior, 1 Intermediate, 2 Senior, 3 Expert

# Master Data
## Persons
- [x] Add a one2many field "Skills" (skill_ids) to fsm.person.skill using fsm_person_id

# Operations
## Orders
- [x] Add a many2many field "Skills" (skill_ids) to hr.skill
- [x] Selecting the template fills in the categories and skills ~~and filter the list of FS persons~~
- [x] ~~Set the FS person automatically using the preferred FS person from the location, if the skills match~~

# Reporting
## Skills
- [x] Add a menu item "Skills" in Reporting for fsm.person.skill
- [x] Add a pivot view for fsm.person.skill

**Comment by dreispt** [comment]
Should Skills reuse the existing HR module? https://github.com/OCA/hr/blob/11.0/hr_skill/models/hr_skill.py
We could reuse it, even if we don't use Employees.
cc @max3903 @robertrottermann

**Comment by max3903** [comment]
@dreispt Yes

**Comment by dreispt** [comment]
@robertrottermann Thoughts? This would affect #26

**Comment by max3903** [comment]
@dreispt FYI, I made a suggestion of improvement for skills https://github.com/OCA/hr/issues/503
