### ISSUE TITLE
[14.0] Creating a new "Worker", the "Related Partner" required field is not editable and is not populated

### ISSUE THREAD

**Issue by dreispt** [OCA/field-service#907]
![image](https://user-images.githubusercontent.com/1246629/153629731-17ae31f1-dff0-45b2-9b35-ccf553d29f96.png)

**Comment by robinhli** [comment]
same issue for 13.0

**Comment by pleirb** [comment]
> ![image](https://user-images.githubusercontent.com/1246629/153629731-17ae31f1-dff0-45b2-9b35-ccf553d29f96.png)

It's a problem in the fsm.person.form view
Just change readonly from 1 to 0 on this line:
`<field name="partner_id" groups="base.group_no_one" readonly="0"/>`

**Comment by dreispt** [comment]
This might have been initially designed to have the Workers created from a button on Partners.

**Comment by pleirb** [comment]
> Esto podría haber sido diseñado inicialmente para tener a los Trabajadores creados a partir de un botón en Partners.

In v16 I also do not have the option to convert a partner into a worker enabled.
![imagen](https://github.com/user-attachments/assets/daa9213a-7a0a-479a-89b4-bf66ad822419)
