### ISSUE TITLE
[14.0] fieldservice: smart buttons not working

### ISSUE THREAD

**Issue by ygol** [OCA/field-service#915]
## Modules Affected
[x] - fieldservice #916 
[ ] - fieldservice_account
[ ] - fieldservice_account_payment
[ ] - fieldservice_agreement
[ ] - fieldservice_distribution
[ ] - fieldservice_isp_account
[x] - fieldservice_partner_multi_relation #917 
[x] - fieldservice_project #918 
[ ] - fieldservice_purchase
[ ] - fieldservice_sale
[ ] - fieldservice_stock

## Describe the bug
most Smart buttons are not working. getting error:
```
Access Error
×
You are not allowed to access 'Action Window' (ir.actions.act_window) records.

This operation is allowed for the following groups:
	- Administration/Settings

Contact your administrator to request access if necessary. 

```
## To Reproduce
**Affected versions**:  14.0

1. go to runbot and set demo user as field service administrator
2. log as demo user go to master data / location or workers
3. click on smart buttons

**Expected behavior**
clicking on smart buttons opens the targeted window

**Additional context**
tested on runbot

**Comment by ygol** [comment]
Hi @max3903 should I do one PR per module or would it be ok to do one PR addressing this problem for all the modules in the repo at once? TIA

**Comment by smangukiya** [comment]
@ygol : One PR per module is expected. Thank you for your good work!

**Comment by brian10048** [comment]
@ygol Thank you for the fixes.  I updated your original comment and noted all the modules that appear to be affected by this bug.  Are you available to submit PRs for the remaining modules?

**Comment by ygol** [comment]
> @ygol Thank you for the fixes. I updated your original comment and noted all the modules that appear to be affected by this bug. Are you available to submit PRs for the remaining modules?

Yes I am

**Comment by ygol** [comment]
Hi @brian10048 pls reopen.
