### ISSUE TITLE
[14.0] fieldservice: unit test"s of CRM module are not passing due to the fieldservice module

### ISSUE THREAD

**Issue by castalie-dev** [OCA/field-service#922]
When we start Odoo  executing the unit test for crm and fieldservice module using this command :
**`./odoo/bin -d testDB -i crm,fieldservice  --test-enable --log-level=debug`**
the most of UT in CRM  module are failed 
Error message
**odoo.exceptions.AccessError: You are not allowed to access 'Field Service Location' (fsm.location) records.

This operation is allowed for the following groups:
	- Field Service/Dispatcher
	- Field Service/User (only own documents)

Contact your administrator to request access if necessary.**

**Comment by castalie-dev** [comment]
To slove this issue we need to add a sudo() on one line of code 
partners_with_loc_ids = (self.env["fsm.location"]**.sudo()**.search([("active", "in", [False, True]), ("partner_id", "in", self.ids)]).mapped("partner_id")).ids

file to be edited: /field-service/fieldservice/models/res_partner.py in the line 60 , by adding that .sudo()

**Comment by jbjour** [comment]
Hello,

I have the same issue on an Odoo.sh environment. This fix seems to be right. 
We need it to be implemented ! :+1:

**Comment by marouensa** [comment]
Hello ,
We also need this fix to implement the Odoo.sh environment.

**Comment by abdelaziz556** [comment]
Hello ,
I have the same problem

**Comment by Abdelmajidhnen** [comment]
Hello ,
I have the same problem. I need this fix

**Comment by smangukiya** [comment]
@Vandan-OSI Can you please work on this issue?

CC: @murtuzasaleh

**Comment by castalie-dev** [comment]
@Vandan-OSI @murtuzasaleh is there any update please ?

**Comment by brian10048** [comment]
> To slove this issue we need to add a sudo() on one line of code partners_with_loc_ids = (self.env["fsm.location"]**.sudo()**.search([("active", "in", [False, True]), ("partner_id", "in", self.ids)]).mapped("partner_id")).ids
> 
> file to be edited: /field-service/fieldservice/models/res_partner.py in the line 60 , by adding that .sudo()

@castalie-dev 
The fix you recommend was merged with this PR #890 

Can you verify you have this [commit](https://github.com/OCA/field-service/commit/489ca36c6b43ded9f41d891dc27ed6b55fcb6ebf) and then recheck for the error

**Comment by castalie-dev** [comment]
Thanks
