### ISSUE TITLE
Does this work for version 15?

### ISSUE THREAD

**Issue by fauks** [OCA/field-service#928]
Sorry I'm really new to all of this. I just installed odoo 15 locally and added the field-service addon (git checkout 15.0) and updated odoo.conf. 

When I update the list on "apps" under developer mode,  I still don't see it. 

Do I need to downgrade to 14?

Thanks

**Comment by brian10048** [comment]
@fauks Version 15 is not yet migrated.  Version 14 has many apps migrated. You can downgrade to 14 and you will be able to install field service  

You can follow #854 where we track the migration status to v15.
