### ISSUE TITLE
[Question][14.0] How to follow equipment ?

### ISSUE THREAD

**Issue by Steff-mwl** [OCA/field-service#930]
In an order, you can only add equipment already in the location which I don't understand. There are fields 'assigned location' and 'current location' in the equipment. I would have imagine that if the equipment current location is the assigned location then it can be added to an order, which once started change the current location to the order location and back to the assigned location once finished.

So I don't really understand the equipment workflow here, could you please explain it to me ?
My use case is pretty simple : a team (workers aren't assigned in a team ?) goes to the order location with equipment, does the job and get back with the equipment.

**Comment by marcos-mendez** [comment]
You can remove the equipment from its original designed location for repair for example, so current location is not the same as assigned location. That is why you have this type of fields. Hope i have helped.
