### ISSUE TITLE
Fieldservice to Sale Orders

### ISSUE THREAD

**Issue by TheCloneMaster** [OCA/field-service#936]
Most of the time, while technicians are working on a FSM order, spare parts are needed.

There is already a module for fsm stock requests, but it doesn't allow to request approval from customer in case he has to pay for the spares...

Is there any module that covers this use case?
If not, we will work on it and create a PR here, but first would like any advice from current contributors
I envision a mix between fsm stock requests but linked to Sales, and the parts flow on the "repair" module with the ability to generate SO like reports.

Regards,
-Mario

**Comment by brian10048** [comment]
#1027
