### ISSUE TITLE
[BUG] - 14.0 Field-Service Location Builder Settings not being saved

### ISSUE THREAD

**Issue by marcos-mendez** [OCA/field-service#961]
## Module
field-service

## Describe the bug
When setting Field-service Location Builder in the Settings Menu After clicking save it doesn't save and the location builder features are not allowed neither generated
[Screencast from 30-09-2022 12:07:52.webm](https://user-images.githubusercontent.com/38361760/193301059-d1ae8ae1-bae9-4d40-97b7-e4310d3c5247.webm)

**Comment by marcos-mendez** [comment]
This was tested in Odoo Bot Instance http://oca-field-service-14-0-6233229ced9f.runboat.odoo-community.org/web?#action=90&cids=1&id=&menu_id=4&model=res.config.settings&view_type=form

**Comment by marcos-mendez** [comment]
@max3903 if you guide me i can try to fix this

**Comment by marcos-mendez** [comment]
@marcelsavegnago maybe this was the problem i was telling you the other day. The field -service builder generates those fields

https://github.com/OCA/field-service/blob/14.0/fieldservice/models/res_config_settings.py#L41

**Comment by marcelsavegnago** [comment]
@marcos-mendez fieldservice_location_builder has not been migrated to 14.0. The way to fix your problem is to migrate the module to 14.0

**Comment by marcelsavegnago** [comment]
@marcos-mendez This configuration that is implemented here is for installing the module. However, if the module does not exist in the instance, the system does nothing.

https://github.com/OCA/field-service/blob/14.0/fieldservice/models/res_config_settings.py#L41

**Comment by marcelsavegnago** [comment]
12.0
https://github.com/OCA/field-service/tree/12.0/fieldservice_location_builder
